import { desc, eq, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { notifications, postLikes, posts, profiles } from "../../../db/schema";
import { hashJson } from "../auth/hash";
import { type Proof, verifyAndConsumeProof } from "../auth/verify";
import {hasOwnerSession,OWNER_WALLET} from "../../owner-access-auth";
export async function GET(){try{return Response.json({posts:await getDb().select().from(posts).where(eq(posts.moderationStatus,"approved")).orderBy(desc(posts.id)).limit(30)})}catch{return Response.json({posts:[]},{status:503})}}
export async function POST(request:Request){const bypass=await hasOwnerSession(request),p=await request.json() as Proof&{body?:string},body=(p.body||"").trim();if(!body||body.length>500)return Response.json({error:"Post must be 1–500 characters"},{status:400});const hash=await hashJson({body}),wallet=bypass?OWNER_WALLET:await verifyAndConsumeProof(p,"post:create","lumberyard",hash);if(!wallet)return Response.json({error:"Connect and sign this post"},{status:403});const db=getDb(),[a]=await db.select({displayName:profiles.displayName}).from(profiles).where(eq(profiles.wallet,wallet)).limit(1),[recent]=await db.select({createdAt:posts.createdAt}).from(posts).where(eq(posts.authorWallet,wallet)).orderBy(desc(posts.id)).limit(1);if(!a)return Response.json({error:"Create a profile before posting"},{status:403});if(recent&&Date.now()-Date.parse(recent.createdAt)<15000)return Response.json({error:"Wait a few seconds before posting again"},{status:429});const [post]=await db.insert(posts).values({author:a.displayName,authorWallet:wallet,body}).returning();return Response.json({post},{status:201})}
export async function PATCH(request:Request){const bypass=await hasOwnerSession(request),p=await request.json() as Proof&{id?:number};if(!Number.isInteger(p.id))return Response.json({error:"Valid post required"},{status:400});const hash=await hashJson({id:p.id}),wallet=bypass?OWNER_WALLET:await verifyAndConsumeProof(p,"post:like",String(p.id),hash);if(!wallet)return Response.json({error:"Sign in to like this board"},{status:403});const db=getDb(),[target]=await db.select().from(posts).where(eq(posts.id,p.id!)).limit(1);if(!target||target.moderationStatus!=="approved")return Response.json({error:"Post not found"},{status:404});try{await db.insert(postLikes).values({postId:p.id!,wallet})}catch{return Response.json({error:"You already liked this board"},{status:409})}const [post]=await db.update(posts).set({likes:sql`${posts.likes} + 1`}).where(eq(posts.id,p.id!)).returning();if(post&&target.authorWallet!==wallet){const [actor]=await db.select({handle:profiles.handle}).from(profiles).where(eq(profiles.wallet,wallet)).limit(1);await db.insert(notifications).values({recipientWallet:target.authorWallet,actorWallet:wallet,actorHandle:actor?.handle||"",kind:"like",body:`@${actor?.handle||"a board"} liked your post.`,href:"/"})}return Response.json({post})}
