import {and,desc,eq,inArray,or} from "drizzle-orm";
import {getDb} from "../../../db";
import {posts,profileComments,profileRelations,profiles} from "../../../db/schema";
import {hashJson} from "../auth/hash";
import {type Proof,verifyAndConsumeProof} from "../auth/verify";

type Item={id:string;type:"post"|"knock"|"profile";author:string;handle:string;avatarUrl:string;body:string;createdAt:string;targetHandle?:string;likes?:number};
async function buildFeed(connectionWallet?:string){const db=getDb();let allowedWallets:string[]|null=null,allowedHandles:string[]|null=null;if(connectionWallet){const relations=await db.select().from(profileRelations).where(eq(profileRelations.ownerWallet,connectionWallet)),followed=[...new Set(relations.filter(r=>r.kind==="friend"||r.kind==="favorite"||r.kind==="top8").map(r=>r.targetHandle))],blocked=new Set(relations.filter(r=>r.kind==="block").map(r=>r.targetHandle));allowedHandles=followed.filter(h=>!blocked.has(h));const people=allowedHandles.length?await db.select({wallet:profiles.wallet,handle:profiles.handle}).from(profiles).where(inArray(profiles.handle,allowedHandles)):[];allowedWallets=[connectionWallet,...people.map(p=>p.wallet)]}
 const profileRows=connectionWallet?(allowedHandles?.length?await db.select({wallet:profiles.wallet,handle:profiles.handle,displayName:profiles.displayName,avatarUrl:profiles.avatarUrl,mood:profiles.mood,moodText:profiles.moodText,updatedAt:profiles.updatedAt}).from(profiles).where(and(eq(profiles.moderationStatus,"approved"),inArray(profiles.handle,allowedHandles))).orderBy(desc(profiles.updatedAt)).limit(30):[]):await db.select({wallet:profiles.wallet,handle:profiles.handle,displayName:profiles.displayName,avatarUrl:profiles.avatarUrl,mood:profiles.mood,moodText:profiles.moodText,updatedAt:profiles.updatedAt}).from(profiles).where(eq(profiles.moderationStatus,"approved")).orderBy(desc(profiles.updatedAt)).limit(30),byWallet=new Map(profileRows.map(p=>[p.wallet,p]));
 const postRows=connectionWallet&&allowedWallets?.length?await db.select().from(posts).where(inArray(posts.authorWallet,allowedWallets)).orderBy(desc(posts.id)).limit(40):await db.select().from(posts).orderBy(desc(posts.id)).limit(40);
 const knockRows=connectionWallet?(allowedHandles?.length?await db.select().from(profileComments).where(or(inArray(profileComments.profileHandle,allowedHandles),inArray(profileComments.authorWallet,allowedWallets!))).orderBy(desc(profileComments.id)).limit(40):[]):await db.select().from(profileComments).orderBy(desc(profileComments.id)).limit(40);
 const missingWallets=[...new Set([...postRows.map(p=>p.authorWallet),...knockRows.map(c=>c.authorWallet)].filter(Boolean).filter(w=>!byWallet.has(w)))],missing=missingWallets.length?await db.select({wallet:profiles.wallet,handle:profiles.handle,displayName:profiles.displayName,avatarUrl:profiles.avatarUrl,mood:profiles.mood,moodText:profiles.moodText,updatedAt:profiles.updatedAt}).from(profiles).where(and(eq(profiles.moderationStatus,"approved"),inArray(profiles.wallet,missingWallets))):[];missing.forEach(p=>byWallet.set(p.wallet,p));const targetHandles=[...new Set(knockRows.map(c=>c.profileHandle))],approvedTargets=new Set(targetHandles.length?(await db.select({handle:profiles.handle}).from(profiles).where(and(eq(profiles.moderationStatus,"approved"),inArray(profiles.handle,targetHandles)))).map(p=>p.handle):[]),avatar=(p:{handle:string;avatarUrl:string})=>p.avatarUrl?`/api/avatar?handle=${p.handle}`:"/plank-classic.jpeg";
 const items:Item[]=[...postRows.filter(p=>p.moderationStatus==="approved"&&byWallet.has(p.authorWallet)).map(p=>{const author=byWallet.get(p.authorWallet)!;return{id:`post-${p.id}`,type:"post" as const,author:author.displayName,handle:author.handle,avatarUrl:avatar(author),body:p.body,likes:p.likes,createdAt:p.createdAt}}),...knockRows.filter(c=>c.moderationStatus==="approved"&&byWallet.has(c.authorWallet)&&approvedTargets.has(c.profileHandle)).map(c=>{const author=byWallet.get(c.authorWallet)!;return{id:`knock-${c.id}`,type:"knock" as const,author:author.displayName,handle:author.handle,avatarUrl:avatar(author),targetHandle:c.profileHandle,body:c.body,createdAt:c.createdAt}}),...profileRows.map(p=>({id:`profile-${p.handle}-${p.updatedAt}`,type:"profile" as const,author:p.displayName,handle:p.handle,avatarUrl:avatar(p),body:`${p.mood}: ${p.moodText}`,createdAt:p.updatedAt}))];return items.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,60)}
export async function GET(){try{return Response.json({items:await buildFeed()})}catch{return Response.json({items:[],error:"The live feed is warming up."},{status:503})}}
export async function POST(request:Request){const payload=await request.json() as Proof&{mode?:string},data={mode:"connections"},hash=await hashJson(data),wallet=await verifyAndConsumeProof(payload,"feed:connections","lumberyard",hash);if(!wallet)return Response.json({error:"Connect and sign to load your connections feed."},{status:403});try{return Response.json({items:await buildFeed(wallet)})}catch{return Response.json({items:[],error:"Your connections feed is temporarily unavailable."},{status:503})}}
