import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('./runtime-shell.mjs',import.meta.url),'utf8');
const text=source.slice(source.indexOf('export function openNativeToolPanel'),source.indexOf('// UI-only bridge from the local account shell')).replace('export ','');
const open=runInNewContext(text+';openNativeToolPanel');
test('native tool commands preserve loading/modal guards and open map without toggling it closed',()=>{
 let loading=false,modal=false,gear=0,focus=0;const settings={open:false,querySelector:()=>({focus(){focus++;}})};
 const root={querySelector:s=>s==='dialog[open]'?modal:s==='button.charm-runtime-enter'?loading:s==='.charm-runtime-settings'?settings:{focus(){focus++;}},querySelectorAll:()=>[]};
 const host={charmvilleMapReady:false};
 assert.equal(open('map',root,host,()=>gear++),false);
 host.charmvilleMapReady=true;assert.equal(open('map',root,host,()=>gear++),true);assert.equal(host.charmvilleOpenMap,true);
 host.charmvilleMapOpen=true;host.charmvilleOpenMap=false;open('map',root,host,()=>gear++);assert.equal(host.charmvilleOpenMap,false);
 loading=true;assert.equal(open('gear',root,host,()=>gear++),false);assert.equal(gear,0);
 loading=false;assert.equal(open('gear',root,host,()=>gear++),true);assert.equal(gear,1);
 assert.equal(open('settings',root,host,()=>gear++),true);assert.equal(settings.open,true);
 modal=true;assert.equal(open('gear',root,host,()=>gear++),false);
 assert.equal(open('canvas',root,host,()=>gear++),false);assert.ok(focus>0);
});
test('menu capability advertisement is limited to the accepted parent handshake',()=>{
 let listener;const sent=[];const parent={postMessage:(message,origin)=>sent.push({message,origin})};
 const window={parent,addEventListener:(type,fn)=>{if(type==='message')listener=fn;}};
 runInNewContext(source.slice(source.indexOf('// UI-only bridge from the local account shell')),{window,document:{},compactHostedShell(){},accountOrigin:null});
 listener({source:{},origin:'http://localhost:3017',get data(){throw Error('foreign source read');}});
 listener({source:parent,origin:'https://other.test',get data(){throw Error('foreign origin read');}});
 assert.equal(sent.length,0);
 listener({source:parent,origin:'http://localhost:3017',data:{type:'charmville:host-ready'}});
 assert.equal(sent.length,1);assert.equal(sent[0].origin,'http://localhost:3017');
 assert.equal(sent[0].message.type,'charmville:menu-capabilities');assert.deepEqual(Array.from(sent[0].message.panels),['gear','map','settings']);
});
