import { Pool } from 'pg';
import { chromium } from 'playwright';
import { createHash, randomBytes } from 'node:crypto';
const db=new URL(process.env.CHARMVILLE_TEST_DATABASE_URL);
const base=new URL(process.env.CHARMVILLE_TEST_BASE_URL||'http://localhost:3017');
if(!['localhost','127.0.0.1'].includes(db.hostname)||!['localhost','127.0.0.1'].includes(base.hostname))throw Error('Local isolated verification only');
const pool=new Pool({connectionString:db.href});
const wallet='0x'+randomBytes(20).toString('hex'),token=randomBytes(32).toString('hex');
const handle='art_'+randomBytes(5).toString('hex');
const browser=await chromium.launch({headless:true});
let page;
try{
 await pool.query("INSERT INTO plankspace_profiles(wallet,handle,display_name,moderation_status,layout_json) VALUES($1,$2,'Charmville art check','approved','[\"feed\",\"friends\"]')",[wallet,handle]);
 await pool.query('INSERT INTO plankspace_wallet_sessions(token_hash,wallet,expires_at) VALUES($1,$2,$3)',[createHash('sha256').update(token).digest('hex'),wallet,new Date(Date.now()+3600000).toISOString()]);
 page=await browser.newPage({viewport:{width:1280,height:1400}});
 const foreign=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/x/'))foreign.push(r.url())});
 await page.addInitScript(({wallet,token})=>{localStorage.setItem('plankspace-terms-2026-08-22-v1','accepted');localStorage.setItem('plankspace-session:'+wallet,token);localStorage.setItem('plankspace-last-verified-wallet',wallet);window.ethereum={isMetaMask:true,request:async({method})=>{if(method==='eth_accounts'||method==='eth_requestAccounts')return[wallet];if(method==='eth_chainId')return'0x1237';if(method==='personal_sign')throw Error('Unexpected fresh signature');return null;},on(){},removeListener(){}};},{wallet,token});
 await page.goto(new URL('/u/'+handle,base).href);
 const porch=page.getByRole('region',{name:'Charmville porch'});
 await porch.getByRole('button',{name:'Claim your lot',exact:true}).click();
 await page.locator('[data-plot="0"][data-stage="ripe"]').waitFor();
 await porch.getByRole('button',{name:'Gather',exact:true}).click();
 const bag=page.getByRole('dialog',{name:'Satchel'});await bag.waitFor();
 await bag.getByRole('button',{name:'Close satchel'}).click();
 await porch.getByRole('button',{name:'Plant here',exact:true}).click();
 await page.locator('[data-plot="0"][data-stage="seedling"]').waitFor();
 await porch.scrollIntoViewIfNeeded();
 const frame=page.locator('[data-plot="1"] image').nth(1);
 const state=await frame.evaluate(e=>getComputedStyle(e).animationPlayState);if(state!=='running')throw Error('Visible animation not running');
 await page.emulateMedia({reducedMotion:'reduce'});if(await frame.evaluate(e=>getComputedStyle(e).animationName)!=='none')throw Error('Reduced motion ignored');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await porch.getByRole('button',{name:'Arrange scenery',exact:true}).click();
 await page.getByRole('button',{name:'Place tree at 1, 2',exact:true}).click();
 await porch.getByRole('button',{name:'Save scenery',exact:true}).click();
 await porch.getByRole('button',{name:'Arrange scenery',exact:true}).waitFor();
 await page.reload();await porch.getByRole('button',{name:'Arrange scenery',exact:true}).waitFor();
 await porch.scrollIntoViewIfNeeded();
 await porch.screenshot({path:'.charmville-isometric-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await porch.getByRole('button',{name:'Choose plot 2',exact:true}).click();
 await porch.screenshot({path:'.charmville-isometric-mobile.png'});
 await porch.getByRole('button',{name:'Satchel',exact:true}).click();
 await bag.waitFor();if(await page.getByRole('dialog',{name:'Satchel'}).count()!==1)throw Error('Multiple satchel sheets');
 await bag.screenshot({path:'.charmville-isometric-satchel.png'});
 if(foreign.length)throw Error('Unexpected foreign API calls');
 const result=await page.request.get(new URL('/api/charmville/'+handle,base).href,{headers:{authorization:'Bearer '+token}});const yard=await result.json();
 if(yard.decorations.find(item=>item.id===0)?.y!==1)throw Error('Scenery did not persist after reload');
 if(yard.inventory.faces.find(s=>s.face==='stalk')?.qty!=='3')throw Error('Harvest balance incorrect');
 if(yard.inventory.seeds.find(s=>s.face==='stalk')?.qty!=='2')throw Error('Seed return/replant incorrect');
 console.log('PASS: claim, harvest without signature, seed return, replant, animation, reduced motion, 390px sheet, no X API.');
}catch(error){if(page){console.error((await page.locator("body").innerText()).slice(-2500));await page.screenshot({path:".charmville-browser-error.png"});}throw error;}finally{await browser.close();await pool.query('DELETE FROM plankspace_wallet_sessions WHERE wallet=$1',[wallet]);for(const table of ['charmville_receipts','charmville_plots','charmville_seeds','charmville_stacks','charmville_yards'])await pool.query(`DELETE FROM ${table} WHERE profile_id=(SELECT id FROM plankspace_profiles WHERE wallet=$1)`,[wallet]);await pool.query('DELETE FROM plankspace_profiles WHERE wallet=$1',[wallet]);await pool.end();}
