"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {getPlankLoveWalletState} from "../plank-love-wallet";
import {savedWalletProof,walletProof} from "../auth-client";
import {useWoodstockLive} from "./live-provider";

type Room={slug:string;title:string;description:string;hostHandle:string;jitsiRoom:string;status:string};
type Member={handle:string;role:string;micStatus:string;avatarUrl:string};
export default function LiveLounge({slug}:{slug:string}){const [room,setRoom]=useState<Room|null>(null),[members,setMembers]=useState<Member[]>([]),[me,setMe]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const live=useWoodstockLive();const load=useCallback(()=>fetch(`/api/live-rooms?slug=${encodeURIComponent(slug)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Lounge unavailable");setRoom(data.room);setMembers(data.members||[])}).catch(error=>setMessage(error instanceof Error?error.message:"Lounge unavailable")),[slug]);useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);useEffect(()=>{if(me&&room&&!members.some(member=>member.handle===me)){queueMicrotask(()=>{live.leave();setMessage("The host removed you from this lounge.")})}},[live,me,members,room]);
 const action=async(action:string,targetHandle="")=>{if(!room)return;setBusy(true);setMessage("");try{const state=await getPlankLoveWalletState(),wallet=state.address?.toLowerCase();if(!wallet)throw new Error("Connect your Plank.love wallet first.");const data={action,slug:room.slug,title:"",description:"",targetHandle},proof=await walletProof(wallet,"live-room:manage",room.slug,data),response=await fetch("/api/live-rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Lounge action failed");if(action==="join"){const session=await savedWalletProof(wallet),profileResponse=await fetch("/api/profiles",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...session,wallet})}),profileData=await profileResponse.json();const handle=profileData.profile?.handle||"plank-listener",displayName=profileData.profile?.displayName||handle;setMe(handle);live.join(room,displayName,result.role||"listener")}if(action==="leave"||action==="end")live.leave();await load()}catch(error){setMessage(error instanceof Error?error.message:"Lounge action failed")}finally{setBusy(false)}};
 if(!room)return <main className="live-lounge missing"><p>{message||"Loading the lounge…"}</p><Link href="/woodstock">Back to Woodstock</Link></main>;const mine=members.find(member=>member.handle===me),isHost=mine?.role==="host",speakers=members.filter(member=>member.role==="host"||member.role==="speaker"),listeners=members.filter(member=>member.role==="listener");return <main className="live-lounge"><header><Link className="brand" href="/plankspace">plank<span>space</span><sup>β</sup></Link><Link href="/woodstock">← Live directory</Link></header><section className="live-stage"><div className="live-stage-heading"><div><span className="live-dot">LIVE</span><h1>{room.title}</h1><p>{room.description}</p><small>Hosted by <Link href={`/u/${room.hostHandle}`}>@{room.hostHandle}</Link></small></div><div><b>🎙 {speakers.length}</b><b>👂 {listeners.length}</b></div></div><div className="speaker-grid">{speakers.map(member=><article key={member.handle}><img src={member.avatarUrl||"/plank-classic.jpeg"} alt=""/><strong>{member.handle}</strong><span>{member.role}</span>{isHost&&member.role!=="host"&&<div><button onClick={()=>action("demote",member.handle)}>Move to audience</button><button onClick={()=>action("remove",member.handle)}>Remove</button></div>}</article>)}</div><h2>Listeners</h2><div className="listener-grid">{listeners.map(member=><article key={member.handle}><img src={member.avatarUrl||"/plank-classic.jpeg"} alt=""/><span>{member.handle}</span>{member.micStatus==="requested"&&<em>hand raised</em>}{isHost&&<div>{member.micStatus==="requested"&&<button onClick={()=>action("approve-mic",member.handle)}>Approve Mic</button>}<button onClick={()=>action("remove",member.handle)}>Remove</button></div>}</article>)}</div><div className="live-controls">{!mine?<button disabled={busy} onClick={()=>action("join")}>Join as Listener</button>:<>{mine.role==="listener"&&mine.micStatus!=="requested"&&<button disabled={busy} onClick={()=>action("request-mic")}>✋ Grab the Mic</button>}<button onClick={live.toggleMute}>{live.muted?"Unmute":"Mute"}</button><button disabled={busy} onClick={()=>action("leave")}>Leave</button>{isHost&&<button className="danger" onClick={()=>action("end")}>End Lounge</button>}</>}</div>{message&&<p className="live-message" role="status">{message}</p>}</section></main>}
