"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";import { useCallback,useEffect,useState } from "react";import { walletProof } from "../auth-client";import { connectPlankLoveWallet,getPlankLoveWalletState } from "../plank-love-wallet";import { useLiveAudio } from "./live-provider";
type Member={id:number;handle:string;role:"host"|"speaker"|"listener";micStatus:string;requestedMic:boolean;removed:boolean};type Room={slug:string;title:string;description:string;hostHandle:string;jitsiRoom:string;status:string};
export default function LiveLounge({slug}:{slug:string}){
 const audio=useLiveAudio(),[memberId,setMemberId]=useState(0),[room,setRoom]=useState<Room|null>(null),[members,setMembers]=useState<Member[]>([]),[message,setMessage]=useState(""),me=members.find(x=>x.id===memberId),isHost=me?.role==="host";
 const load=useCallback(async()=>{const response=await fetch(`/api/live-rooms?room=${encodeURIComponent(slug)}`),body=await response.json();if(!response.ok)throw new Error(body.error||"Lounge unavailable");setRoom(body.room);setMembers(body.members||[]);const current=(body.members||[]).find((x:Member)=>x.id===memberId);if(current){audio.setRole(current.role);if(current.micStatus==="muted")audio.forceMute()}},[audio,memberId,slug]);
 const act=useCallback(async(action:string,targetMemberId=0,micStatus="muted")=>{const state=await getPlankLoveWalletState();let address=state.address;if(!address)address=await connectPlankLoveWallet();const data={action,room:slug,title:"",description:"",targetMemberId,micStatus},proof=await walletProof(address,"live-room:act",slug,data),response=await fetch("/api/live-rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Lounge action failed");return body},[slug]);
 const enter=async()=>{setMessage("");try{const result=await act("join"),identity=result.member as Member&{displayName:string;avatarUrl:string};setMemberId(identity.id);setRoom(result.room);await audio.join(result.room.jitsiRoom,{handle:identity.handle,displayName:identity.displayName,avatarUrl:identity.avatarUrl},identity.role);await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not enter lounge")}};
 useEffect(()=>{queueMicrotask(()=>{void load().catch(e=>setMessage(e.message))})},[load]);useEffect(()=>{if(!audio.room)return;const id=setInterval(()=>{void act("heartbeat").then(result=>{if(result.member?.id)setMemberId(result.member.id);return load()}).catch(e=>{audio.leave();setMessage(e instanceof Error?e.message:"Lounge session ended")})},10000);return()=>clearInterval(id)},[act,audio,load]);
 const moderate=async(action:string,target:number)=>{try{await act(action,target);await load()}catch(e){setMessage(e instanceof Error?e.message:"Moderation failed")}};const toggle=async()=>{audio.toggleMic();await act("mic-status",0,audio.muted?"unmuted":"muted").catch(()=>undefined)};
 return <div className="live-lounge-page"><header><Link className="brand" href="/woodstock">← Woodstock</Link><b>{room?.title||"Loading lounge…"}</b><span>● LIVE</span></header><main><section className="lounge-stage"><small>AUDIO-FIRST LOUNGE</small><h1>{room?.title}</h1><p>{room?.description}</p><div className="lounge-counts"><b>{members.filter(x=>x.role==="host"||x.role==="speaker").length} on mic</b><b>{members.filter(x=>x.role==="listener").length} listening</b></div>{!audio.room?<button className="page-button" type="button" onClick={enter}>Enter Live Audio</button>:<div className="live-controls"><button type="button" onClick={()=>audio.setExpanded(true)}>Open Audio Stage</button>{me?.role==="listener"?<button type="button" onClick={()=>act("request-mic").then(load)}>✋ Grab the Mic</button>:<button type="button" onClick={toggle}>{audio.muted?"🎙 Unmute":"🔇 Mute"}</button>}<button type="button" onClick={audio.leave}>Leave</button></div>}{message&&<p role="alert">{message}</p>}</section><section className="lounge-people"><h2>In the Lounge</h2>{members.filter(x=>!x.removed).map(member=><article key={member.id} data-live-role={member.role}><a href={`/u/${member.handle}`}><img src={`/api/avatar?handle=${member.handle}`} alt=""/><b>@{member.handle}</b></a><span>{member.role} · {member.micStatus}{member.requestedMic?" · hand raised":""}</span>{isHost&&member.role!=="host"&&<div className="host-controls">{member.role==="listener"?<button type="button" onClick={()=>moderate("promote",member.id)}>Approve Mic</button>:<><button type="button" onClick={()=>moderate("mute",member.id)}>Mute</button><button type="button" onClick={()=>moderate("demote",member.id)}>Move to Listener</button></>}<button type="button" onClick={()=>moderate("remove",member.id)}>Remove</button></div>}</article>)}</section>{isHost&&<button className="close-lounge" type="button" onClick={()=>moderate("close",0)}>End Lounge</button>}</main></div>;
}
