"use client";
import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from "react";
type Role="host"|"speaker"|"listener";
type Identity={handle:string;displayName:string;avatarUrl?:string};
type JitsiApi={executeCommand:(name:string,...args:unknown[])=>void;addListener:(name:string,fn:(event:unknown)=>void)=>void;dispose:()=>void};
declare global {interface Window {JitsiMeetExternalAPI?:new(domain:string,options:Record<string,unknown>)=>JitsiApi}}
type LiveContext={room:string;role:Role;joined:boolean;muted:boolean;expanded:boolean;join:(room:string,identity:Identity,role:Role)=>Promise<void>;leave:()=>void;toggleMic:()=>void;setRole:(role:Role)=>void;setExpanded:(value:boolean)=>void;forceMute:()=>void};
const Context=createContext<LiveContext|null>(null),domain=process.env.NEXT_PUBLIC_JITSI_DOMAIN||"meet.jit.si";
async function loadJitsi(){if(window.JitsiMeetExternalAPI)return;await new Promise<void>((resolve,reject)=>{const old=document.querySelector<HTMLScriptElement>("script[data-plankspace-jitsi]");if(old){old.addEventListener("load",()=>resolve(),{once:true});old.addEventListener("error",()=>reject(new Error("Jitsi failed to load")),{once:true});return}const el=document.createElement("script");el.src=`https://${domain}/external_api.js`;el.async=true;el.dataset.plankspaceJitsi="1";el.onload=()=>resolve();el.onerror=()=>reject(new Error("Jitsi failed to load"));document.head.appendChild(el)})}
export function LiveAudioProvider({children}:{children:ReactNode}){
 const holder=useRef<HTMLDivElement>(null),api=useRef<JitsiApi|null>(null),[room,setRoom]=useState(""),[roleState,setRoleState]=useState<Role>("listener"),[joined,setJoined]=useState(false),[muted,setMuted]=useState(true),[expanded,setExpanded]=useState(false);
 const forceMute=useCallback(()=>{if(!muted)api.current?.executeCommand("toggleAudio");setMuted(true)},[muted]);
 const setRole=useCallback((role:Role)=>{setRoleState(role);if(role==="listener")forceMute()},[forceMute]);
 const leave=useCallback(()=>{api.current?.dispose();api.current=null;setJoined(false);setRoom("");setExpanded(false);setMuted(true)},[]);
 const join=useCallback(async(nextRoom:string,identity:Identity,role:Role)=>{leave();await loadJitsi();if(!holder.current||!window.JitsiMeetExternalAPI)throw new Error("Audio room could not start");setRoom(nextRoom);setRoleState(role);setExpanded(true);api.current=new window.JitsiMeetExternalAPI(domain,{roomName:nextRoom,parentNode:holder.current,userInfo:{displayName:`@${identity.handle}`,email:""},configOverwrite:{startWithAudioMuted:true,startWithVideoMuted:true,prejoinPageEnabled:false,disableDeepLinking:true,disableSelfView:true,toolbarButtons:[],notifications:[],p2p:{enabled:true}},interfaceConfigOverwrite:{MOBILE_APP_PROMO:false,SHOW_JITSI_WATERMARK:false,SHOW_BRAND_WATERMARK:false,TOOLBAR_ALWAYS_VISIBLE:false}});api.current.addListener("videoConferenceJoined",()=>setJoined(true));api.current.addListener("audioMuteStatusChanged",event=>setMuted(Boolean((event as {muted?:boolean}).muted)));api.current.addListener("readyToClose",leave)},[leave]);
 const toggleMic=useCallback(()=>{if(roleState!=="listener")api.current?.executeCommand("toggleAudio")},[roleState]);useEffect(()=>()=>api.current?.dispose(),[]);
 return <Context.Provider value={{room,role:roleState,joined,muted,expanded,join,leave,toggleMic,setRole,setExpanded,forceMute}}>{children}<aside className={`live-audio-stage ${expanded?"expanded":"minimized"}`} aria-label="Woodstock audio stage" hidden={!room}><header><b>Woodstock · {room}</b><span>{joined?"Live audio connected":"Connecting…"}</span><button type="button" onClick={()=>setExpanded(!expanded)}>{expanded?"Minimize":"Open"}</button><button type="button" onClick={leave}>Leave</button></header><div ref={holder} className="jitsi-media"/><footer><button type="button" onClick={toggleMic} disabled={roleState==="listener"}>{roleState==="listener"?"Listener — Grab the Mic first":muted?"Unmute Mic":"Mute Mic"}</button><span>{roleState}</span></footer></aside></Context.Provider>;
}
export function useLiveAudio(){const value=useContext(Context);if(!value)throw new Error("useLiveAudio must be used inside LiveAudioProvider");return value}
