"use client";
/* eslint-disable @next/next/no-location-assign-relative-destination */
import Link from "next/link";import { useEffect,useState } from "react";import { walletProof } from "../auth-client";import { connectPlankLoveWallet,getPlankLoveWalletState } from "../plank-love-wallet";
type Room={slug:string;title:string;description:string;hostHandle:string;participantCount:number};
export default function WoodstockDirectory(){
 const [rooms,setRooms]=useState<Room[]>([]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[message,setMessage]=useState("");
 const load=()=>fetch("/api/live-rooms").then(r=>r.json()).then(x=>setRooms(x.rooms||[])).catch(()=>undefined);useEffect(()=>{void load();const id=setInterval(load,15000);return()=>clearInterval(id)},[]);
 const create=async()=>{setMessage("");try{const state=await getPlankLoveWalletState();let wallet=state.address;if(!wallet)wallet=await connectPlankLoveWallet();const room=title.toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,48),data={action:"create",room,title,description,targetMemberId:0,micStatus:"muted"},proof=await walletProof(wallet,"live-room:act",room,data),response=await fetch("/api/live-rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not create lounge");window.location.href=`/woodstock/${body.room}`}catch(e){setMessage(e instanceof Error?e.message:"Could not create lounge")}};
 return <div className="woodstock-shell"><header><Link className="brand" href="/plankspace">plank<span>space</span><sup>β</sup></Link><b>WOODSTOCK LIVE</b></header><main><section className="woodstock-hero"><small>LIVE SOCIAL AUDIO</small><h1>The Grove is on air.</h1><p>Create a real audio lounge, listen quietly, or grab the mic. Your PlankSpace profile is your identity.</p><div className="create-lounge"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Lounge name" maxLength={80}/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="What are we talking about?" maxLength={240}/><button type="button" onClick={create} disabled={!title.trim()}>Create Live Lounge</button></div>{message&&<p role="alert">{message}</p>}</section><section className="live-directory" id="woodstock-live-directory"><div className="head"><h2>Live Lounges</h2><span>{rooms.length} on air</span></div>{rooms.length?<div className="live-room-grid">{rooms.map(room=><article className="live-room-card" data-live-room={room.slug} key={room.slug}><div className="live-dot">● LIVE</div><h3>{room.title}</h3><p>{room.description||"Pull up a board and listen in."}</p><span>Hosted by @{room.hostHandle} · {room.participantCount} listening</span><Link href={`/woodstock/${room.slug}`}>Enter Lounge</Link></article>)}</div>:<p className="public-empty">No lounges are live yet. Start the first one.</p>}</section></main></div>;
}
