import { createHash, randomBytes } from "node:crypto";
import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { profiles, xAccounts, xOAuthStates } from "../../../../db/schema";
import { hashJson } from "../../auth/hash";
import { type Proof, verifyAndConsumeProof } from "../../auth/verify";
import { getXProvider } from "../../../x/provider";

export async function POST(request:Request){const payload=await request.json() as Proof&{handle?:string},handle=String(payload.handle||"").toLowerCase(),wallet=await verifyAndConsumeProof(payload,"x:connect",handle,await hashJson({handle}));if(!wallet)return Response.json({error:"Signed profile-owner proof required"},{status:403});const db=getDb(),[profile]=await db.select({wallet:profiles.wallet}).from(profiles).where(eq(profiles.handle,handle)).limit(1);if(!profile||profile.wallet!==wallet)return Response.json({error:"Only the profile owner may connect X"},{status:403});if(process.env.PLANKSPACE_X_PROVIDER==="development"){const account=await getXProvider().connect({handle});await db.insert(xAccounts).values({wallet,profileHandle:handle,xUserId:account.id,xUsername:account.username}).onConflictDoUpdate({target:xAccounts.wallet,set:{profileHandle:handle,xUserId:account.id,xUsername:account.username,updatedAt:new Date().toISOString()}});return Response.json({connected:true,username:account.username,provider:"development"})}const clientId=process.env.X_CLIENT_ID,redirectUri=process.env.X_REDIRECT_URI;if(!clientId||!redirectUri)return Response.json({error:"Live X OAuth is not configured"},{status:503});const state=randomBytes(24).toString("base64url"),verifier=randomBytes(48).toString("base64url"),challenge=createHash("sha256").update(verifier).digest("base64url");await db.insert(xOAuthStates).values({state,wallet,profileHandle:handle,pkceVerifier:verifier,expiresAt:new Date(Date.now()+10*60_000).toISOString()});const url=new URL("https://x.com/i/oauth2/authorize");url.searchParams.set("response_type","code");url.searchParams.set("client_id",clientId);url.searchParams.set("redirect_uri",redirectUri);url.searchParams.set("scope","tweet.read tweet.write users.read offline.access");url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");return Response.json({authorizationUrl:url.toString(),provider:"live"})}
