import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { notifications, profileComments, profileRelations, profiles } from "../../../db/schema";
import { normalizePostMedia } from "../../post-media";
import { hashJson } from "../auth/hash";
import { type Proof, verifyAndConsumeProof } from "../auth/verify";
const clean=(v:string)=>v.toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,24);
export async function GET(request:Request){const handle=clean(new URL(request.url).searchParams.get("handle")||"");if(!handle)return Response.json({comments:[]});try{return Response.json({comments:await getDb().select().from(profileComments).where(and(eq(profileComments.profileHandle,handle),eq(profileComments.moderationStatus,"approved"))).orderBy(desc(profileComments.id)).limit(30)})}catch{return Response.json({comments:[]},{status:503})}}
export async function POST(request:Request){
 const p=await request.json() as Proof&{handle?:string;body?:string;mediaUrl?:string;mediaType?:string;mediaAlt?:string},handle=clean(p.handle||""),body=(p.body||"").trim().slice(0,500);if(!handle||!body)return Response.json({error:"A real knock needs words"},{status:400});
 let media;try{media=normalizePostMedia(p)}catch(e){return Response.json({error:e instanceof Error?e.message:"Invalid media attachment"},{status:400})}
 const data={handle,body,mediaUrl:media.mediaUrl,mediaType:media.mediaType,mediaAlt:media.mediaAlt},hash=await hashJson(data),wallet=await verifyAndConsumeProof(p,"comment:create",handle,hash);if(!wallet)return Response.json({error:"Connect and sign to leave a knock"},{status:403});
 const db=getDb(),[a]=await db.select({displayName:profiles.displayName,handle:profiles.handle}).from(profiles).where(eq(profiles.wallet,wallet)).limit(1),[target]=await db.select({wallet:profiles.wallet,status:profiles.moderationStatus}).from(profiles).where(eq(profiles.handle,handle)).limit(1),[recent]=await db.select({createdAt:profileComments.createdAt}).from(profileComments).where(eq(profileComments.authorWallet,wallet)).orderBy(desc(profileComments.id)).limit(1);if(!a)return Response.json({error:"Create a profile before commenting"},{status:403});if(target?.status!=="approved")return Response.json({error:"This profile is not accepting knocks"},{status:404});const [blocked]=await db.select({id:profileRelations.id}).from(profileRelations).where(and(eq(profileRelations.ownerWallet,target.wallet),eq(profileRelations.targetHandle,a.handle),eq(profileRelations.kind,"block"))).limit(1);if(blocked)return Response.json({error:"This board is not accepting your knocks"},{status:403});if(recent&&Date.now()-Date.parse(recent.createdAt)<15000)return Response.json({error:"Wait a few seconds before knocking again"},{status:429});const [comment]=await db.insert(profileComments).values({profileHandle:handle,author:a.displayName,authorWallet:wallet,body,...media}).returning();if(target.wallet!==wallet)await db.insert(notifications).values({recipientWallet:target.wallet,actorWallet:wallet,actorHandle:a.handle,kind:"knock",body:`@${a.handle} knocked: ${body.slice(0,100)}`,href:`/u/${handle}#comments`});return Response.json({comment},{status:201})}
