const ALLOWED_PROPERTIES=/^(background(?:-color|-image|-position|-repeat|-size|-attachment)?|color|filter|font(?:-family|-size|-style|-weight)?|border(?:-(?:top|right|bottom|left))?(?:-color|-style|-width|-radius)?|box-shadow|text-shadow|text-decoration|text-transform|letter-spacing|line-height|opacity)$/i;
const panels=".classic-profile :where(.box,.content,.identity,.status,.player,.lounge-intro,.public-knocks article)";
const aliases:Record<string,string>={body:".classic-profile[class]",html:".classic-profile[class]",table:panels,tr:panels,td:panels,".contacttable":".classic-profile .contact",".profileinfo":".classic-profile .identity",".profile-info":".classic-profile .identity",".interestsanddetails":".classic-profile .interests",".userprofiledetail":".classic-profile .identity",".blurbs":".classic-profile .about",".friendspace":".classic-profile .friendspace",".friends":".classic-profile .friendspace",".friendscomments":".classic-profile .comments",".latestblogentry":".classic-profile .feed",".extendednetwork":".classic-profile .status",".bodycontent":".classic-profile>main",".container":".classic-profile>main",".clearfix":".classic-profile .public-modules",".heading":".classic-profile :where(.head,.box h2,.about>h2)",".url-info":".classic-profile .url",".inner":panels,".details-table":".classic-profile .interests",".comments-table":".classic-profile .comments",".comment-replies":".classic-profile .comments article",".home-actions":".classic-profile .contact",".logo":".classic-profile .brand","#q":".classic-profile .directory-search input"};
function scopeSelector(raw:string){const selector=raw.trim();if(!selector||selector.includes("@"))return "";const alias=aliases[selector.toLowerCase()];if(alias)return alias;if(/\b(?:table|tr|td)\b/i.test(selector))return /contacttable/i.test(selector)?".classic-profile .contact":panels;const normalized=selector.replace(/\b(?:html|body)\b/gi,".classic-profile").replace(/\.contacttable\b/gi,".contact").replace(/\.profileinfo\b/gi,".identity").replace(/\.interestsanddetails\b/gi,".interests").replace(/\.userprofiledetail\b/gi,".identity").replace(/\.blurbs\b/gi,".about").replace(/\.friendspace\b/gi,".friendspace").replace(/\.friendscomments\b/gi,".comments").replace(/\.latestblogentry\b/gi,".feed").replace(/\.extendednetwork\b/gi,".status").replace(/\.bodycontent\b/gi,">main").replace(/(?:\.classic-profile\s*){2,}/g,".classic-profile ").trim();return normalized.startsWith(".classic-profile")?normalized:`.classic-profile ${normalized}`}
function safeValue(raw:string){const value=raw.replace(/http:\/\//gi,"https://").replace(/(^|[\s:,])([0-9a-f]{6})(?=$|[\s,)])/gi,"$1#$2");if(/(?:javascript:|expression\s*\(|behavior\s*:|@import|<|>|\\)/i.test(value))return "";const urls=[...value.matchAll(/url\s*\(\s*(['"]?)(.*?)\1\s*\)/gi)];if(urls.some(([, ,url])=>!/^https:\/\//i.test(url)&&!/^\/api\/layout-asset\?key=[a-z0-9/_-]+$/i.test(url)&&!/^data:image\/(?:png|jpeg|webp|gif);base64,/i.test(url)))return "";return value.trim()}
/** Converts old-school layout CSS into visual-only rules scoped to one profile. */
export function customProfileCss(html:string){const css=[...html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)].map(match=>match[1]).join("\n").replace(/\/\*[\s\S]*?\*\//g,"");if(!css)return "";const output:string[]=[];for(const match of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)){const selectors=match[1].split(",").map(scopeSelector).filter(Boolean);if(!selectors.length)continue;const declarations:string[]=[];for(const declaration of match[2].split(";")){const colon=declaration.indexOf(":");if(colon<1)continue;const property=declaration.slice(0,colon).trim(),value=safeValue(declaration.slice(colon+1).replace(/!important/gi,"").trim());if(property.toLowerCase()==="filter"&&/url\s*\(/i.test(value))continue;if(ALLOWED_PROPERTIES.test(property)&&value)declarations.push(`${property}:${value}!important`)}const pageEffect=selectors.some(selector=>/^\.classic-profile(?:::before|\[class\]::before)$/.test(selector));if(pageEffect)declarations.push('content:""!important','display:block!important','position:absolute!important','inset:0!important','pointer-events:none!important','z-index:1!important','animation:plankspace-crt-flicker 6s steps(2,end) infinite!important');if(declarations.length)output.push(`${selectors.join(",")} {${declarations.join(";")}}`)}return output.join("\n").slice(0,24000)}

/** True when custom code contains content beyond page-level CSS and comments. */
export function hasVisibleCustomContent(html:string){
 const markup=html.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"").replace(/<!--[\s\S]*?-->/g,"").trim();
 if(!markup)return false;
 if(/<(?:img|picture|svg|canvas|video|audio|marquee|table|ul|ol|form|button|hr)\b/i.test(markup))return true;
 return markup.replace(/<[^>]*>/g,"").replace(/&(?:nbsp|#160);/gi,"").trim().length>0;
}
