"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element, react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import Link from "next/link";
import {connectPlankLoveWallet} from "./plank-love-wallet";
import {walletProof} from "./auth-client";
import AdminNavLink from "./admin-nav-link";
import {MediaAttachment,MediaComposer} from "./post-media-ui";
import type {PostMedia} from "./post-media";
type Item={id:string;type:"post"|"knock"|"profile";author:string;handle:string;avatarUrl:string;body:string;createdAt:string;targetHandle?:string;likes?:number;mediaUrl?:string;mediaType?:string;mediaAlt?:string};
const emptyMedia:PostMedia={mediaUrl:"",mediaType:"",mediaAlt:""};
export default function HomeFeed(){
 const [items,setItems]=useState<Item[]>([]),[mode,setMode]=useState<"global"|"connections">("global"),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[media,setMedia]=useState<PostMedia>(emptyMedia);
 const loadGlobal=()=>{setLoading(true);setMode("global");fetch("/api/feed").then(r=>r.json()).then(d=>{setItems(d.items||[]);setMessage(d.error||"")}).catch(()=>setMessage("The lumberyard feed is unavailable.")).finally(()=>setLoading(false))};
 useEffect(loadGlobal,[]);
 const loadConnections=async()=>{setLoading(true);setMessage("");try{const wallet=await connectPlankLoveWallet(),data={mode:"connections"},proof=await walletProof(wallet,"feed:connections","lumberyard",data),d=await fetch("/api/feed",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}).then(r=>r.json());if(d.error)throw new Error(d.error);setItems(d.items||[]);setMode("connections")}catch(e){setMessage(e instanceof Error?e.message:"Could not load connections.")}finally{setLoading(false)}};
 const post=async()=>{if(!body.trim())return;setBusy(true);setMessage("");try{const wallet=await connectPlankLoveWallet(),data={body:body.trim(),...media},proof=await walletProof(wallet,"post:create","lumberyard",data),d=await fetch("/api/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}).then(r=>r.json());if(d.error)throw new Error(d.error);setBody("");setMedia(emptyMedia);loadGlobal()}catch(e){setMessage(e instanceof Error?e.message:"Post failed.")}finally{setBusy(false)}};
 return <div className="home-feed">
  <header><Link className="brand" href="/plankspace">plank<span>space</span></Link><nav><Link href="/browse">Browse Boards</Link><Link href="/search">Search</Link><Link href="/woodstock">Woodstock</Link><Link href="/planks-list">Planks List</Link><Link href="/board-mail">Board Mail</Link><AdminNavLink/></nav><div className="account"><Link href="/profile-editor">My Profile</Link></div></header>
  <main><aside><div className="home-plank"><i/><i/></div><small>YOUR PLANKSPACE HOME</small><h1>The Lumberyard</h1><p>Live posts, mood changes, profile updates, and knocks from boards across the community.</p><a href="/u/degenwaffle">Visit DegenWaffle</a><a href="/planks-list">My Planks List</a><a href="/profile-editor">Customize My Space</a></aside>
  <section><div className="feed-hero"><small>LIVE FROM THE LOUNGE</small><h2>What&apos;s on your grain?</h2><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={500} placeholder="Post an update…"/><MediaComposer value={media} onChange={setMedia} idPrefix="home-feed"/><button disabled={busy||!body.trim()} onClick={post}>{busy?"Posting…":"Post to Lumberyard"}</button></div><div className="feed-tabs" role="tablist"><button role="tab" aria-selected={mode==="global"} onClick={loadGlobal}>Everyone</button><button role="tab" aria-selected={mode==="connections"} onClick={loadConnections}>My Connections</button></div>{message&&<p className="feed-message" role="status">{message}</p>}{loading?<p className="feed-loading">Loading fresh sawdust…</p>:<div className="activity-feed">{items.map(item=><article key={item.id} className={`activity-${item.type}`}><a className="activity-avatar" href={`/u/${item.handle}`}><img src={item.avatarUrl||"/plank-classic.jpeg"} alt=""/></a><div><small>{item.type.toUpperCase()}</small><h3><a href={`/u/${item.handle}`}>{item.author}</a></h3><p>{item.body}</p><MediaAttachment mediaUrl={item.mediaUrl} mediaType={item.mediaType} mediaAlt={item.mediaAlt}/><time>{new Date(item.createdAt).toLocaleString()}</time>{typeof item.likes==="number"&&<b>♡ {item.likes}</b>}</div></article>)}</div>}</section></main>
  <footer><b>plankspace</b><nav><a href="/about">About</a><a href="/board-safety">Board Safety</a><a href="/grain-policy">Grain Policy</a><a href="/help">Help</a></nav><small>Wallet-owned profiles · Durable community history</small></footer>
 </div>;
}
