"use client";

import { useState } from "react";
import { connectPlankLoveWallet } from "./plank-love-wallet";
import { walletProof } from "./auth-client";

type Relation={targetHandle:string;kind:string;rank:number};
type DirectoryProfile={handle:string;displayName:string};

export default function TopEightManager(){
 const [wallet,setWallet]=useState(""),[handle,setHandle]=useState(""),[items,setItems]=useState<string[]>([]),[profiles,setProfiles]=useState<DirectoryProfile[]>([]),[visible,setVisible]=useState(true),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const loadLists=async(address:string,profileHandle:string)=>{const [relations,directory]=await Promise.all([fetch(`/api/relations?wallet=${address}`).then(r=>r.json()),fetch("/api/profiles").then(r=>r.json())]);setItems((relations.relations||[]).filter((x:Relation)=>x.kind==="top8").sort((a:Relation,b:Relation)=>a.rank-b.rank).map((x:Relation)=>x.targetHandle));setProfiles((directory.profiles||[]).filter((p:DirectoryProfile)=>p.handle!==profileHandle))};
 const connect=async()=>{setBusy(true);setMessage("");try{const address=await connectPlankLoveWallet(),proof=await walletProof(address,"profile:read",address,{wallet:address}),result=await fetch("/api/profiles",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(proof)}).then(r=>r.json()),profile=result.profile as {handle:string;themeJson:string}|undefined;if(!profile)throw new Error("No profile belongs to this wallet yet.");setWallet(address);setHandle(profile.handle);try{setVisible(JSON.parse(profile.themeJson||"{}").showTop8!==false)}catch{}await loadLists(address,profile.handle)}catch(e){setMessage(e instanceof Error?e.message:"Could not open Top 8 manager.")}finally{setBusy(false)}};
 const change=async(targetHandle:string,enabled:boolean)=>{setBusy(true);setMessage("");try{const data={targetHandle,kind:"top8",enabled},proof=await walletProof(wallet,"relation:set",targetHandle,data),result=await fetch("/api/relations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}).then(r=>r.json());if(result.error)throw new Error(result.error);await loadLists(wallet,handle);setSelected("");setMessage(enabled?`@${targetHandle} added to your Top 8.`:`@${targetHandle} removed.`)}catch(e){setMessage(e instanceof Error?e.message:"Top 8 update failed.")}finally{setBusy(false)}};
 const toggle=async(next:boolean)=>{setBusy(true);setMessage("");try{const data={showTop8:next},proof=await walletProof(wallet,"profile:preferences",handle,data),result=await fetch("/api/profile-preferences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}).then(r=>r.json());if(result.error)throw new Error(result.error);setVisible(next);setMessage(next?"Your Top 8 is visible.":"Your Top 8 is hidden from your public page.")}catch(e){setMessage(e instanceof Error?e.message:"Visibility update failed.")}finally{setBusy(false)}};
 const available=profiles.filter(p=>!items.includes(p.handle));
 return <section className="top8-editor"><div className="top8-heading"><div><small>FRIEND SPACE</small><h2>Customize your Top 8</h2><p>Choose up to eight approved planks and decide whether the section appears on your public profile.</p></div>{wallet&&<label className="top8-toggle"><input type="checkbox" checked={visible} disabled={busy} onChange={e=>void toggle(e.target.checked)}/><span>{visible?"Visible":"Hidden"}</span></label>}</div>{!wallet?<button type="button" onClick={connect} disabled={busy}>{busy?"Opening…":"Open My Top 8 Manager"}</button>:<><ol>{items.map((item,index)=><li key={item}><b>#{index+1}</b><a href={`/u/${item}`} target="_blank">@{item}</a><button type="button" disabled={busy} onClick={()=>void change(item,false)}>Remove</button></li>)}{!items.length&&<li className="top8-empty">Your Top 8 is empty.</li>}</ol><div className="top8-add"><select value={selected} disabled={busy||items.length>=8} onChange={e=>setSelected(e.target.value)}><option value="">Choose an approved plank…</option>{available.map(p=><option key={p.handle} value={p.handle}>{p.displayName} (@{p.handle})</option>)}</select><button type="button" disabled={busy||!selected||items.length>=8} onClick={()=>void change(selected,true)}>Add to Top 8</button></div>{items.length>=8&&<small>All eight slots are filled. Remove someone before adding another.</small>}</>}{message&&<p role="status">{message}</p>}</section>;
}
