"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {savedWalletProof} from '@/integrations/plankspace-app/app/auth-client';
type Availability={canProvision?:boolean;available:boolean;balls:number;reason:string|null};
type Command={action:'provision'}|{action:'throw';requestId:string;encounterId:string;revision:string;actorEpoch:number};
const button='min-h-11 rounded-lg border border-line px-4 py-2 text-gold-300 focus-visible:outline-2 focus-visible:outline-gold-300 disabled:opacity-50';
export default function CapturePanel({wallet,encounterId,revision,actorEpoch,onChanged,onReceipt,onAvailability}:{wallet:string;encounterId:string;revision:string;actorEpoch:number;onChanged:()=>void;onReceipt?:(receipt:unknown)=>void;onAvailability?:(available:boolean)=>void}){
 const [state,setState]=useState<Availability|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[retry,setRetry]=useState(false),[captured,setCaptured]=useState(false);
 const pending=useRef<Command|null>(null),abort=useRef<AbortController|null>(null),epoch=useRef(0),running=useRef(false);
 const request=useCallback(async(command?:Command)=>{if(running.current&&!command)return;abort.current?.abort();const controller=new AbortController();abort.current=controller;const version=++epoch.current;running.current=true;if(command)setBusy(true);
 try{const proof=await savedWalletProof(wallet);if(controller.signal.aborted)return;if(!proof.sessionToken)throw new Error('Reconnect your account.');const response=await fetch('/api/charmville/world/capture',{method:command?'POST':'GET',headers:{authorization:`Bearer ${proof.sessionToken}`,'Content-Type':'application/json'},body:command?JSON.stringify(command):undefined,cache:'no-store',mode:'same-origin',redirect:'error',signal:controller.signal});const data=await response.json();if(controller.signal.aborted||version!==epoch.current)return;
 if(!response.ok){if(command&&[400,403,404,409,422].includes(response.status)){pending.current=null;setRetry(false);}throw new Error(data.error??'Capture could not be confirmed.');}
 if(command){pending.current=null;setRetry(false);if(command.action==='throw'){onReceipt?.(data);setCaptured(data.captured===true);setMessage(data.captured?'Poochyena captured and saved to your collection. Open Party to choose a slot.':`Poochyena broke free after ${data.shakes} shakes. Your ball was used.`);window.dispatchEvent(new Event('charmville:companion-health-changed'));}else setMessage('Three local test balls are available. This supply is granted once.');setState(previous=>previous?{...previous,balls:data.balls,available:false,canProvision:false}:null);onChanged();}else setState(data);
 }catch(error){if(!controller.signal.aborted&&version===epoch.current){if(command)setRetry(!!pending.current);setMessage(error instanceof Error?error.message:'Capture unavailable.');}}
 finally{if(version===epoch.current){running.current=false;setBusy(false);}}
 },[wallet,onChanged,onReceipt]);
 useEffect(()=>{const epochs=epoch;let disposed=false;void Promise.resolve().then(()=>{if(!disposed)void request();});const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!pending.current)void request();},2000);return()=>{disposed=true;clearInterval(timer);++epochs.current;abort.current?.abort();running.current=false;};},[request]);
 const canThrow=!!state?.available&&!busy&&!retry&&!captured;
 const throwBall=useCallback(()=>{if(!state?.available||busy||retry||captured||pending.current)return;const command:Command={action:'throw',requestId:crypto.randomUUID(),encounterId,revision,actorEpoch};pending.current=command;void request(command);},[state?.available,busy,retry,captured,encounterId,revision,actorEpoch,request]);
 useEffect(()=>{onAvailability?.(canThrow);return()=>onAvailability?.(false);},[canThrow,onAvailability]);
 useEffect(()=>{window.addEventListener('charmville:capture-request',throwBall);return()=>window.removeEventListener('charmville:capture-request',throwBall);},[throwBall]);
 return <section aria-label="Capture creature" className="my-3 rounded-lg border border-line p-3"><h4 className="font-bold text-gold-300">Capture</h4><p className="my-2 text-sm text-cream-muted">{state?`${state.balls} Poké Balls`:'Checking supplies…'}</p>{state?.canProvision&&<button type="button" className={`${button} mb-2`} disabled={busy||retry} onClick={()=>{if(pending.current)return;const command:Command={action:'provision'};pending.current=command;void request(command);}}>Claim 3 local test balls</button>}{!captured&&<button type="button" className={button} disabled={busy||retry||!state?.available} onClick={throwBall}>Throw Poké Ball</button>}{state?.reason&&!captured&&<p className="mt-2 text-sm text-cream-muted">{state.reason}</p>}{retry&&<button type="button" className={`${button} mt-2`} disabled={busy} onClick={()=>{if(pending.current)void request(pending.current);}}>Retry capture action</button>}{message&&<p role="status" className="mt-2 text-sm">{message}</p>}</section>;
}
