"use client";
import {useEffect,useRef,useState} from 'react';
export type Participant={profileId:string;handle:string;inRange?:boolean;boundCreature:null|{id:string;speciesId:number;hp?:number;maxHp?:number;statuses?:string[]}};
export type CombatEvent={eventId:string;turn:number;actorProfileId:string;log:{actor:string;targetId?:string;move:string;damage:number;appliedDamage?:number;critical:boolean;miss:boolean}[]};
const names:Record<number,string>={277:'Treecko',280:'Torchic',283:'Mudkip',25:'Pikachu',133:'Eevee',286:'Poochyena'};
function Portrait({speciesId,hit}:{speciesId:number;hit:boolean}){const name=names[speciesId];return name?<div role="img" aria-label={`${name} source portrait`} data-hit={hit?'committed':undefined} className={`mx-auto h-16 w-16 rounded ${hit?'ring-2 ring-gold-300':''}`} style={{backgroundImage:`url(/charmville/creatures/${name.toLowerCase()}-front.png)`,backgroundPosition:'0 0',backgroundRepeat:'no-repeat',imageRendering:'pixelated'}}/>:null;}
export default function EncounterScene({wild,participants,events,controllerId}:{wild:{id:string;speciesId:number;hp:number;maxHp:number;statuses:string[]};participants:Participant[];events:CombatEvent[];controllerId:string|null}){
 const previous=useRef<string|undefined>(undefined),[hits,setHits]=useState<string[]>([]);
 const eventId=events.at(-1)?.eventId??'';
 const eventLog=JSON.stringify(events.at(-1)?.log??[]);
 useEffect(()=>{const initial=previous.current===undefined;if(previous.current===eventId)return;previous.current=eventId;if(initial||!eventId)return;const logs=JSON.parse(eventLog) as CombatEvent['log'];const targetIds=logs.filter(log=>!log.miss&&(log.appliedDamage??log.damage)>0&&log.targetId).map(log=>log.targetId!);let disposed=false;void Promise.resolve().then(()=>{if(!disposed)setHits(targetIds);});const timer=setTimeout(()=>setHits([]),600);return()=>{disposed=true;clearTimeout(timer);};},[eventId,eventLog]);
 const fighter=participants.find(player=>player.profileId===controllerId)?.boundCreature;
 return <div aria-label="Shared encounter scene" className="my-2"><div className="grid grid-cols-2 gap-3"><div><Portrait speciesId={wild.speciesId} hit={hits.includes(wild.id)}/><p className="text-center text-sm">Wild HP {wild.hp} / {wild.maxHp}</p><meter aria-label="Wild creature HP" min={0} max={wild.maxHp} value={wild.hp} className="w-full"/>{wild.statuses.length>0&&<p className="text-xs">{wild.statuses.join(', ')}</p>}</div>{fighter&&<div><Portrait speciesId={fighter.speciesId} hit={hits.includes(fighter.id)}/>{fighter.hp!==undefined&&fighter.maxHp!==undefined&&<><p className="text-center text-sm">Companion HP {fighter.hp} / {fighter.maxHp}</p><meter aria-label="Shared fighter HP" min={0} max={fighter.maxHp} value={fighter.hp} className="w-full"/></>}{fighter.statuses?.length? <p className="text-xs">{fighter.statuses.join(', ')}</p>:null}</div>}</div><ul aria-label="Encounter players" className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-cream-muted">{participants.filter(player=>player.inRange!==false).map(player=><li key={player.profileId}>@{player.handle} · {player.profileId===controllerId?'Fighting':'Watching'}</li>)}</ul></div>;
}
