"use client";
import Image from 'next/image';
import {useEffect,useState} from 'react';
import styles from './item-dex.module.css';
type Entry={originalEffect?:string;previewUrl?:string;id:string;name:string;source:string;sourceId:string;category:string;revision:string;definition:string;line:number;fields:Record<string,string>;art:{url:string;sha256:string}|null;directions?:{x:number;y:number;frame_width:number;frame_height:number}[]};
function Art({item,large=false}:{item:Entry;large?:boolean}){
 const frame=item.directions?.[0];
 if(!item.art)return <span aria-label="Artwork not mapped">—</span>;
 if(frame)return <span className={styles.crop} role="img" aria-label={item.name} style={{width:frame.frame_width,height:frame.frame_height,backgroundImage:`url(${JSON.stringify(item.art.url)})`,backgroundPosition:`-${frame.x}px -${frame.y}px`,transform:`scale(${large?3:2})`}}/>;
 return <Image unoptimized src={item.previewUrl??item.art.url} width={large?72:48} height={large?72:48} alt=""/>;
}
export default function ItemDex({active}:{active:boolean}){
 const [items,setItems]=useState<Entry[]|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[source,setSource]=useState(''),[selected,setSelected]=useState<string|null>(null),[page,setPage]=useState(0);
 useEffect(()=>{if(!active||items)return;const abort=new AbortController();Promise.all([fetch('/charmville/reference-items/catalog.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('The item archive is unavailable.');return r.json();}),fetch('/charmville/catalog/reference-item-presentations.json',{signal:abort.signal}).then(r=>r.ok?r.json():{items:{}}).catch(()=>({items:{}})),fetch('/charmville/catalog/reference-item-descriptions.json',{signal:abort.signal}).then(r=>r.ok?r.json():{items:{}}).catch(()=>({items:{}}))]).then(([data,presentations,descriptions])=>{if(!Array.isArray(data.items))throw Error('The item archive could not be read.');setItems(data.items.filter((item:Entry)=>item.art&&item.sourceId!=='ITEM_NONE'&&!/^\?+$/.test(item.name)).map((item:Entry)=>({...item,previewUrl:presentations.items?.[item.id]?.url,originalEffect:descriptions.items?.[item.id]?.text})));setError('');}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[active,items]);
 const matches=(items??[]).filter(item=>(!source||item.source===source)&&`${item.name} ${item.sourceId} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
 const pages=Math.max(1,Math.ceil(matches.length/24)),current=Math.min(page,pages-1),shown=matches.slice(current*24,current*24+24),item=matches.find(item=>item.id===selected)??shown[0];
 return <section className={styles.dex} aria-label="Item Dex">
  <p className={styles.notice}>Item research · These source entries are not owned charms. Your supplies are in the Bag.</p>
  <div className={styles.filters}><label>Find an item<input value={query} placeholder="Berry, ball, bow…" onChange={e=>{setQuery(e.target.value);setPage(0);setSelected(null);}}/></label><label>Collection<select value={source} onChange={e=>{setSource(e.target.value);setPage(0);setSelected(null);}}><option value="">All collections</option><option value="pokeemerald">Emerald</option><option value="solarus-zsdx">Solarus</option></select></label></div>
  {error&&<p role="alert">{error}</p>}{!items&&!error&&<p role="status">Opening the archive…</p>}
  <div className={styles.body}><div><div className={styles.grid} aria-label="Item entries" onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key))return;const buttons=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('button'));const index=buttons.indexOf(document.activeElement as HTMLButtonElement);if(index<0)return;const delta=event.key==='ArrowUp'?-4:event.key==='ArrowDown'?4:event.key==='ArrowLeft'?-1:1;const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:Math.max(0,Math.min(buttons.length-1,index+delta));event.preventDefault();event.stopPropagation();buttons[next]?.focus();}}>{shown.map(entry=><button key={entry.id} aria-pressed={item?.id===entry.id} onFocus={()=>setSelected(entry.id)} onClick={()=>setSelected(entry.id)} title={entry.name}><span className={styles.art}><Art item={entry}/></span><span>{entry.name}</span></button>)}</div>{items&&matches.length===0&&<p>No matching items. Try a shorter name or another collection.</p>}</div>
  {item&&<article className={styles.detail} aria-label="Selected item"><div className={styles.portrait}><Art item={item} large/></div><h3>{item.name}</h3><p>{item.source==='pokeemerald'?'Pokémon Emerald':'Mystery of Solarus DX'}</p><dl>{item.originalEffect&&<><dt>Original game effect</dt><dd>{item.originalEffect}</dd></>}<dt>Collection pocket</dt><dd>{item.category.replace(/^POCKET_/,'').replaceAll('_',' ').toLowerCase()}</dd><dt>Game availability</dt><dd>Reference only</dd></dl><details><summary>Source record</summary><p>{item.sourceId}</p><p>{item.definition}:{item.line}</p><p>Revision {item.revision}</p><p>Artwork SHA-256 {item.art?.sha256}</p></details></article>}</div>
  <footer className={styles.pages}><button disabled={current===0} onClick={()=>{setPage(current-1);setSelected(null);}}>← Previous</button><span aria-live="polite">{matches.length} entries · {current+1} / {pages}</span><button disabled={current===pages-1} onClick={()=>{setPage(current+1);setSelected(null);}}>Next →</button></footer>
 </section>;
}
