"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {savedWalletProof} from '@/integrations/plankspace-app/app/auth-client';
type Status={eligible:boolean;reason:string|null;eligibleCreatureIds?:string[];pending:null|{requestId:string;creatureId:string;readyAt:string;expiresAt:string};serverNow:string};
type Command={phase:'begin';requestId:string;creatureId:string}|{phase:'commit'|'cancel';requestId:string};
const button='min-h-11 rounded-lg border border-line px-3 py-2 text-gold-300 focus-visible:outline-2 focus-visible:outline-gold-300 disabled:opacity-50';
export default function RestPanel({wallet,creatureId}:{wallet:string;creatureId:string}){
 const [state,setState]=useState<Status|null>(null),[now,setNow]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[retry,setRetry]=useState(false);
 const recovery=useRef<Command|null>(null),epoch=useRef(0),abort=useRef<AbortController|null>(null),running=useRef(false),clock=useRef({server:0,local:0});
 const request=useCallback(async(command?:Command)=>{
  if(running.current&&!command)return;if(command)abort.current?.abort();running.current=true;const current=++epoch.current,controller=new AbortController();abort.current=controller;if(command){setBusy(true);setMessage('');}
  try{const proof=await savedWalletProof(wallet);if(controller.signal.aborted||current!==epoch.current)return;if(!proof.sessionToken){setState(null);return;}const response=await fetch('/api/charmville/companions/rest',{method:command?'POST':'GET',headers:{authorization:`Bearer ${proof.sessionToken}`,'Content-Type':'application/json'},body:command?JSON.stringify(command):undefined,cache:'no-store',mode:'same-origin',redirect:'error',signal:controller.signal});const data=await response.json();if(controller.signal.aborted||current!==epoch.current)return;if(!response.ok){if(command&&[400,403,404,409,422].includes(response.status)){recovery.current=null;setRetry(false);}throw new Error(data.error??'Rest could not be checked.');}setState(data);clock.current={server:Date.parse(data.serverNow),local:Date.now()};setNow(clock.current.server);if(command){recovery.current=null;setRetry(false);if(data.result?.status==='committed'){setMessage('HP and move PP restored.');window.dispatchEvent(new Event('charmville:companion-health-changed'));}else if(data.result?.status==='cancelled')setMessage('Rest cancelled.');}
  }catch(error){if(!controller.signal.aborted&&current===epoch.current){setMessage(error instanceof Error?error.message:'Rest unavailable.');if(command)setRetry(!!recovery.current);}}
  finally{if(current===epoch.current){running.current=false;setBusy(false);}}
 },[wallet]);
 useEffect(()=>{const epochs=epoch;let disposed=false;void Promise.resolve().then(()=>{if(!disposed)void request();});const timer=setInterval(()=>{setNow(clock.current.server+Date.now()-clock.current.local);},1000);const poll=setInterval(()=>{if(document.visibilityState==='visible')void request();},3000);return()=>{disposed=true;clearInterval(timer);clearInterval(poll);++epochs.current;abort.current?.abort();running.current=false;};},[request]);
 function send(command:Command){if(recovery.current)return;recovery.current=command;void request(command);}
 const remaining=state?.pending?Math.max(0,Math.ceil((Date.parse(state.pending.readyAt)-now)/1000)):0;
 const expired=!!state?.pending&&Date.parse(state.pending.expiresAt)<=now;
 return <section aria-label="Companion rest" className="mt-3 border-t border-line pt-3 text-left"><h4 className="font-bold text-gold-300">Rest at home</h4>{state?.pending?<><p className="my-2 text-sm">{state.pending.creatureId===creatureId?'Your companion':'Another companion'} is resting. {expired?'Rest expired. Start again.':remaining?`${remaining}s remaining. Stay still.`:'Ready to recover.'}</p><div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||retry||remaining>0||expired} onClick={()=>send({phase:'commit',requestId:state.pending!.requestId})}>Finish rest</button><button type="button" className={button} disabled={busy||retry} onClick={()=>send({phase:'cancel',requestId:state.pending!.requestId})}>Cancel rest</button></div></>:<><p className="my-2 text-xs text-cream-muted">Restore HP and move PP with 10 seconds of rest at your home.</p><button type="button" className={button} disabled={busy||retry||!state?.eligible||!!(state.eligibleCreatureIds&&!state.eligibleCreatureIds.includes(creatureId))} onClick={()=>send({phase:'begin',requestId:crypto.randomUUID(),creatureId})}>Rest selected companion</button>{state?.reason?<p className="mt-1 text-xs text-cream-muted">{state.reason}</p>:state?.eligibleCreatureIds&&!state.eligibleCreatureIds.includes(creatureId)?<p className="mt-1 text-xs text-cream-muted">Fully rested.</p>:null}</>}{retry&&<button type="button" className={`${button} mt-2`} disabled={busy} onClick={()=>{if(recovery.current)void request(recovery.current);}}>Retry rest action</button>}{message&&<p role="status" className="mt-2 text-xs">{message}</p>}</section>;
}
