"use client";
import {useEffect,useRef,useState} from 'react';
export default function SpectatorSettings({handle,token}:{handle:string;token:string}){
 const [mode,setMode]=useState('public'),[handles,setHandles]=useState(''),[revision,setRevision]=useState<string|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const generation=useRef(0);
 const [loaded,setLoaded]=useState<{path:string;token:string}|null>(null);
 const path='/api/charmville/spectate/'+encodeURIComponent(handle);
 const ready=revision!==null&&loaded?.path===path&&loaded?.token===token;
 useEffect(()=>{const own=++generation.current;const controller=new AbortController();setLoaded(null);setRevision(null);setBusy(false);setMessage('Loading viewing permissions…');fetch(path,{headers:{authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok||!data.owner)throw Error(data.error??'Viewing settings unavailable');if(controller.signal.aborted||own!==generation.current)return;setLoaded({path,token});setMessage('');setMode(data.mode);setHandles(data.allowedHandles.join(', '));setRevision(data.revision);}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>{controller.abort();generation.current++;};},[path,token]);
 async function save(){if(!ready||busy)return;const own=generation.current;setBusy(true);setMessage('');try{const r=await fetch(path,{method:'PUT',headers:{authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({mode,allowedHandles:handles.split(/[\s,]+/).map(s=>s.replace(/^@/,'').toLowerCase()).filter(Boolean),revision})});const data=await r.json();if(!r.ok)throw Error(data.error??'Could not save');if(own!==generation.current)return;setRevision(data.revision);setMessage('Viewing permissions saved.');}catch(e){if(own===generation.current)setMessage(e instanceof Error?e.message:'Could not save');}finally{if(own===generation.current)setBusy(false);}}
 return <details className="rounded-lg border border-line p-3 text-sm"><summary className="cursor-pointer py-2">Profile game viewing</summary><p className="my-2 text-cream-muted">Choose who can watch your gameplay broadcast from your profile. Broadcasting is not connected yet. Viewing does not grant control or home access.</p><label className="block">Audience<select disabled={!ready||busy} className="m-2 rounded border border-line bg-wood-900 p-2" value={mode} onChange={e=>setMode(e.target.value)}><option value="public">Everyone</option><option value="private">Only me</option><option value="allowlist">Allowed profiles</option></select></label>{mode==='allowlist'&&<label className="block">Allowed profile handles<textarea disabled={!ready||busy} className="my-2 block w-full rounded border border-line bg-wood-900 p-2" value={handles} onChange={e=>setHandles(e.target.value)} placeholder="friend_one, friend_two"/></label>}<button className="min-h-11 rounded border border-line px-3" disabled={busy||!ready} onClick={()=>void save()}>{busy?'Saving…':'Save viewing permissions'}</button><p role="status">{message}</p></details>;
}
