"use client";
import {useEffect,useRef,useState} from 'react';
import {savedWalletProof} from '@/integrations/plankspace-app/app/auth-client';
export type TestProfile={wallet:string;token:string;handle:string;expiresAt:string;posts:{id:number;body:string}[]};
export default function TestPartyPanel({wallet,onChanged,onCreate}:{wallet:string;onChanged:()=>void;onCreate?:(profile:TestProfile)=>void|Promise<void>}){
 const [status,setStatus]=useState<{eligible:boolean;granted:boolean}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const prepared=useRef<TestProfile|null>(null),generation=useRef(0),running=useRef(false);
 useEffect(()=>{const current=++generation.current;let disposed=false;if(process.env.NODE_ENV!=='development'||!['localhost','127.0.0.1'].includes(window.location.hostname))return;void(async()=>{const proof=await savedWalletProof(wallet);if(!proof.sessionToken)return;const response=await fetch('/api/charmville/local-playtest/party',{method:'POST',headers:{authorization:`Bearer ${proof.sessionToken}`,'Content-Type':'application/json'},body:JSON.stringify({action:'capabilities'}),cache:'no-store',mode:'same-origin',redirect:'error'});if(response.ok&&!disposed&&current===generation.current)setStatus(await response.json());})().catch(()=>{});return()=>{disposed=true;};},[wallet]);
 async function load(){if(running.current||!status)return;running.current=true;setBusy(true);setMessage('');const current=generation.current;try{let token:string|undefined;
  if(status.eligible){token=(await savedWalletProof(wallet)).sessionToken;}else{if(!onCreate)return;if(!prepared.current){const response=await fetch('/api/charmville/local-playtest',{method:'POST',mode:'same-origin',redirect:'error'});const data=await response.json();if(!response.ok)throw new Error(data.error??'Test profile unavailable.');prepared.current=data;}token=prepared.current?.token;}
  if(!token)throw new Error('Sign in again.');
  const authenticated={authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  const companionsResponse=await fetch('/api/charmville/companions',{headers:authenticated,cache:'no-store',mode:'same-origin',redirect:'error'});const companions=await companionsResponse.json();if(!companionsResponse.ok)throw new Error(companions.error??'Test companion state unavailable.');
  if(!companions.companion){if(!prepared.current)throw new Error('Choose your starter above, then load the test party.');const claim=await fetch(`/api/charmville/${encodeURIComponent(prepared.current.handle)}`,{method:'POST',headers:authenticated,body:JSON.stringify({action:'claim',requestId:crypto.randomUUID()}),mode:'same-origin',redirect:'error'});if(!claim.ok)throw new Error('Test home setup failed. Retry.');const starter=await fetch('/api/charmville/companions',{method:'POST',headers:authenticated,body:JSON.stringify({speciesId:277}),mode:'same-origin',redirect:'error'});if(!starter.ok)throw new Error('Test starter setup failed. Retry.');}
  const response=await fetch('/api/charmville/local-playtest/party',{method:'POST',headers:authenticated,body:JSON.stringify({action:'provision'}),mode:'same-origin',redirect:'error'});const data=await response.json();if(current!==generation.current)return;if(!response.ok)throw new Error(data.error??'Test party unavailable.');if(prepared.current&&onCreate)await onCreate(prepared.current);else{setStatus(data);onChanged();setMessage('Six-member test party loaded.');}
 }catch(error){if(current===generation.current)setMessage(error instanceof Error?error.message:'Test party unavailable.');}finally{running.current=false;if(current===generation.current)setBusy(false);}}
 if(!status||(!status.eligible&&!onCreate))return null;
 return <section aria-label="Local test party" className="mt-3 rounded-lg border border-line p-3"><p className="mb-2 text-xs text-cream-muted">Local testing only. Six distinct companions; no capture, XP or raid completion is granted.</p><button type="button" className="min-h-11 rounded-lg border border-line px-3 py-2 text-gold-300 disabled:opacity-50" disabled={busy||status.granted} onClick={()=>void load()}>{status.granted?'Test party loaded':status.eligible?'Load six-member test party':'Open six-member test profile'}</button>{!status.eligible&&<p className="mt-2 text-xs text-cream-muted">Opens a separate test profile. Your current account stays intact.</p>}{message&&<p role="status" className="mt-2 text-sm">{message}</p>}</section>;
}
