'use client';
/* Source previews deliberately retain original dimensions for inspection. */
/* eslint-disable @next/next/no-img-element */
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useEffect,useState,useSyncExternalStore} from 'react';
import styles from './frontier.module.css';
const World=dynamic(()=>import('./world'),{ssr:false,loading:()=> <div className={styles.loading}>Opening the woodland…</div>});
type Charm={id:string;name:string;emoji:string;chain:string;denom:string;poolId:string};
type Asset={id:string;source:string;path:string;format:string;sha256:string;license:string;preview:string|null};
type Source={id:string;count:number;status:string;upstream:string|null};
const subscribeToHost=()=>()=>{};
const localHostSnapshot=()=>['localhost','127.0.0.1'].includes(window.location.hostname);
const serverHostSnapshot=()=>false;
export default function Frontier(){
 const [tab,setTab]=useState('world');const localReference=useSyncExternalStore(subscribeToHost,localHostSnapshot,serverHostSnapshot);const [charms,setCharms]=useState<Charm[]>([]);const [assets,setAssets]=useState<Asset[]>([]);const [sources,setSources]=useState<Source[]>([]);
 const [query,setQuery]=useState('');const [source,setSource]=useState('');const [selected,setSelected]=useState<Charm|null>(null);const [error,setError]=useState('');const [limit,setLimit]=useState(60);const [assetCount,setAssetCount]=useState(0);
 useEffect(()=>{const controller=new AbortController();Promise.all([fetch('/charmville/library/charms.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Charm library unavailable');return r.json();}),fetch('/charmville/library/summary.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Asset library unavailable');return r.json();})]).then(([c,a])=>{setCharms(c.charms);setAssetCount(a.assetCount);setSources(a.sources);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{if(tab!=='assets'||assets.length)return;const controller=new AbortController();fetch('/charmville/library/catalog.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Could not load asset index');return r.json();}).then(a=>setAssets(a.assets)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[tab,assets.length]);
 const matching=assets.filter(a=>(!source||a.source===source)&&`${a.path} ${a.source} ${a.format}`.toLowerCase().includes(query.toLowerCase()));
 return <main data-market-shell className={styles.root}>
  <header className={styles.header}><div><span className={styles.eyebrow}>PLANKSPACE / THE LIVING FRONTIER</span><h1>Charmville</h1><p>A home to grow. A world to inhabit.</p></div><div className={styles.links}><Link href='/charmville/catalog'>Source item archives ↗</Link><Link href='/charmville/play'>Your saved garden ↗</Link><Link href='/u/charmville_showcase'>PlankSpace profile ↗</Link><Link href='/market'>Marketplank ↗</Link></div></header>
  <nav className={styles.tabs} aria-label='Frontier views'>{[['world','Explore the district'],['charms',`Charm atlas · ${charms.length}`],['assets',`Creator library · ${assetCount.toLocaleString()}`]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setQuery('');setLimit(60);}}>{label}</button>)}</nav>
  <p className={styles.notice}>Development frontier · Solo exploration and device-saved scenery. Shared MMO state and exchange settlement are not active here.</p>
  {localReference&&<section className={styles.library} aria-label='Direct adventure playtest'><h2>Enter the adventure</h2><p>Start directly in Autumn Town with a sword, bow, bombs, boomerang and wand. Original Hero of Dreams artwork and ZQuest combat; no title sequence or story introduction.</p><p><a href='http://localhost:3021/charmville/' target='_blank' rel='noreferrer'>Play the adventure ↗</a> · <a href='http://localhost:3021/create/' target='_blank' rel='noreferrer'>Open quest creation tools ↗</a></p><p>Click Enter the world. Arrow keys move; Z uses the sword; X uses the selected item; Enter opens inventory. This is a source-engine playtest: progress resets, and farming, creatures and shared inventory are not connected yet.</p></section>}
  {error&&<p role='alert'>{error}</p>}
  <div hidden={tab!=='world'}><World active={tab==='world'} onAtlas={()=>setTab('charms')}/></div>
  {tab==='charms'&&<section className={styles.library}><div className={styles.libraryHeading}><div><h2>Every identity has a place.</h2><p>Imported memoji testnet registry. Discovery is separate from ownership, farming issuance, and live trading.</p></div><input aria-label='Search charms' placeholder='Find an emoji, name, or denom…' value={query} onChange={e=>setQuery(e.target.value)}/></div><div className={styles.charmGrid}>{charms.filter(c=>`${c.name} ${c.emoji} ${c.denom}`.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.id} onClick={()=>setSelected(c)}><span className={styles.emoji}>{c.emoji||'◇'}</span><strong>{c.name.replace(/^u/,'')}</strong><small>Discover identity →</small></button>)}</div>{selected&&<div className={styles.detail}><button onClick={()=>setSelected(null)} aria-label='Close charm details'>Close ×</button><h2>{selected.emoji} {selected.name}</h2><p>Source network: {selected.chain}</p><p>Recorded pool: {selected.poolId||'No dedicated pool'}</p><code>{selected.denom}</code><p>This is source metadata, not a verified current price, balance, or mint permission.</p><a href='https://github.com/nocktoshi/memoji-market' target='_blank' rel='noreferrer'>Inspect upstream registry ↗</a></div>}</section>}
  {tab==='assets'&&<section className={styles.library}><div className={styles.libraryHeading}><div><h2>The creator workshop</h2><p>Indexed source files, content hashes, provenance and cleared previews. Indexed does not mean integrated.</p></div><input aria-label='Search assets' placeholder='Search trees, swords, sprites, models…' value={query} onChange={e=>{setQuery(e.target.value);setLimit(60);}}/></div><select aria-label='Asset source' value={source} onChange={e=>{setSource(e.target.value);setLimit(60);}}><option value=''>All source libraries</option>{sources.filter(s=>s.count).map(s=><option key={s.id} value={s.id}>{s.id} · {s.count.toLocaleString()}</option>)}</select><p>{matching.length.toLocaleString()} matching files · previews are available for a curated CC0 subset</p><div className={styles.assetGrid}>{matching.slice(0,limit).map(a=><article key={a.id}>{a.preview?<img src={a.preview} alt={a.path} loading='lazy'/>:<div className={styles.fileType}>{a.format.toUpperCase()}</div>}<strong>{a.path.split('/').pop()}</strong><small>{a.source} · {a.license}</small><details><summary>Provenance</summary><p>{a.path}</p><code>SHA256 {a.sha256}</code>{a.preview&&<a href={a.preview} download>Download cleared asset</a>}</details></article>)}</div>{matching.length>limit&&<button onClick={()=>setLimit(n=>n+60)}>Show 60 more</button>}</section>}
 </main>;
}
