'use client';
/* Three.js objects are intentionally mutable inside the frame loop. */
/* eslint-disable react-hooks/immutability, react-hooks/refs */
import {Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {Canvas,useFrame,useThree,type ThreeEvent} from '@react-three/fiber';
import {Billboard,Html,useGLTF,useTexture} from '@react-three/drei';
import * as THREE from 'three';
import styles from './frontier.module.css';

type Prop={id:number;kind:'orchard-tree'|'blossom-tree';x:number;z:number};
const INITIAL:Prop[]=Array.from({length:24},(_,i)=>({id:i,kind:i%3?'orchard-tree':'blossom-tree',x:i<12?-11+i*2: i%2?-10:10,z:i<12?-8: -5+Math.floor((i-12)/2)*2.2}));
const GRASS=Array.from({length:70},(_,i)=>({id:i,x:-7+(i%10)*1.35,z:2+Math.floor(i/10)*.85}));
const STORE='charmville-frontier-draft-1';
function Model({name,position,scale=1}:{name:string;position:[number,number,number];scale?:number}){
 const {scene}=useGLTF(`/images/charmville/workshop/${name}.glb`);
 const copy=useMemo(()=>{const item=scene.clone(true);item.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});return item;},[scene]);
 return <primitive object={copy} position={position} scale={scale}/>;
}
function Sprite({url,position,width,height}:{url:string;position:[number,number,number];width:number;height:number}){
 const map=useTexture(url);
 return <Billboard position={position}><mesh><planeGeometry args={[width,height]}/><meshBasicMaterial map={map} transparent alphaTest={.08} side={THREE.DoubleSide}/></mesh></Billboard>;
}
function AnimatedActor({location}:{location:React.RefObject<THREE.Vector3>}){
 const maps=useTexture(['/images/charmville/quaternius-farmer/idle/0/0.png',...Array.from({length:8},(_,i)=>`/images/charmville/quaternius-farmer/walk/0/${i}.png`)]);
 const material=useRef<THREE.MeshBasicMaterial>(null);const previous=useRef(new THREE.Vector3());const movedAt=useRef(0);
 useFrame(({clock})=>{if(previous.current.distanceToSquared(location.current)>.00001)movedAt.current=clock.elapsedTime;previous.current.copy(location.current);if(material.current)material.current.map=maps[clock.elapsedTime-movedAt.current<.15?1+Math.floor(clock.elapsedTime*10)%8:0];});
 return <Billboard position={[0,1.05,0]}><mesh><planeGeometry args={[1.6,2.1]}/><meshBasicMaterial ref={material} map={maps[0]} transparent alphaTest={.08} side={THREE.DoubleSide}/></mesh></Billboard>;
}
function Camera({cinema,player}:{cinema:boolean;player:React.RefObject<THREE.Vector3>}){const {camera,size}=useThree();useFrame((_,delta)=>{const focus=size.width<700?player.current:new THREE.Vector3();camera.position.lerp(new THREE.Vector3((cinema?17:18)+focus.x,cinema?11:26,(cinema?22:25)+focus.z),1-Math.exp(-delta*3));camera.lookAt(focus.x,0,focus.z);if(camera instanceof THREE.OrthographicCamera){camera.zoom=THREE.MathUtils.lerp(camera.zoom,size.width<700?26:Math.min(size.width/32,size.height/25),1-Math.exp(-delta*3));camera.updateProjectionMatrix();}});return null;}
function Explorer({target,attack,keys,location,onPosition}:{target:THREE.Vector3;attack:number;keys:React.RefObject<Set<string>>;location:React.RefObject<THREE.Vector3>;onPosition:(x:number,z:number)=>void}){
 const group=useRef<THREE.Group>(null);const blade=useRef<THREE.Group>(null);const started=useRef(0);const previous=useRef(attack);const notify=useRef(0);
 useFrame(({clock},delta)=>{if(!group.current)return;const p=location.current;const dx=Number(keys.current.has('d')||keys.current.has('arrowright'))-Number(keys.current.has('a')||keys.current.has('arrowleft'));const dz=Number(keys.current.has('s')||keys.current.has('arrowdown'))-Number(keys.current.has('w')||keys.current.has('arrowup'));if(dx||dz){p.x+=dx*delta*5;p.z+=dz*delta*5;target.copy(p);}else{const step=target.clone().sub(p);step.y=0;if(step.length()>.12)p.add(step.normalize().multiplyScalar(Math.min(delta*5,p.distanceTo(target))));}p.x=THREE.MathUtils.clamp(p.x,-11,11);p.z=THREE.MathUtils.clamp(p.z,-8,8);group.current.position.copy(p);if(previous.current!==attack){started.current=clock.elapsedTime;previous.current=attack;}const age=clock.elapsedTime-started.current;if(blade.current){blade.current.visible=attack>0&&age<.38;blade.current.rotation.y=age*17;}if(clock.elapsedTime-notify.current>.3){notify.current=clock.elapsedTime;onPosition(p.x,p.z);}});
 return <group ref={group}><AnimatedActor location={location}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,.06,0]}><ringGeometry args={[.36,.42,32]}/><meshBasicMaterial color='#ffe4a0'/></mesh><group ref={blade}><mesh position={[.8,.65,0]} rotation={[0,0,-.5]}><boxGeometry args={[.1,1.5,.12]}/><meshStandardMaterial color='#eef5ef' metalness={.8} roughness={.2}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,.6,0]}><ringGeometry args={[1.1,1.3,32,1,0,Math.PI*1.4]}/><meshBasicMaterial color='#fff3c8' transparent opacity={.65} side={THREE.DoubleSide}/></mesh></group></group>;
}
function Visitor({enabled}:{enabled:boolean}){const group=useRef<THREE.Group>(null);useFrame(({clock})=>{if(group.current){group.current.position.set(Math.sin(clock.elapsedTime*.4)*3,6+Math.sin(clock.elapsedTime)*.3,-1);group.current.rotation.y=clock.elapsedTime*.4;}});return enabled?<group ref={group}><mesh scale={[2,.32,2]}><sphereGeometry args={[1,32,16]}/><meshStandardMaterial color='#c9b9e7' metalness={.85} roughness={.2}/></mesh><mesh position={[0,.35,0]} scale={[.75,.5,.75]}><sphereGeometry args={[1,24,12]}/><meshStandardMaterial color='#9be2d2' emissive='#4b988c' emissiveIntensity={.5}/></mesh><mesh position={[0,-3,0]}><coneGeometry args={[2.2,5.5,32,1,true]}/><meshBasicMaterial color='#c3ffe0' transparent opacity={.1} side={THREE.DoubleSide} depthWrite={false}/></mesh><pointLight color='#a8ffd9' intensity={25} distance={10}/></group>:null;}
function Terrain({onGround,cut,props,onAtlas}:{onGround:(e:ThreeEvent<PointerEvent>)=>void;cut:Set<number>;props:Prop[];onAtlas:()=>void}){
 const turf=useTexture('/images/charmville/workshop/clover-turf.png');
 useEffect(()=>{turf.wrapS=turf.wrapT=THREE.RepeatWrapping;turf.repeat.set(9,7);turf.colorSpace=THREE.SRGBColorSpace;turf.needsUpdate=true;},[turf]);
 return <><mesh position={[0,-.55,0]} receiveShadow><boxGeometry args={[26,1,21]}/><meshStandardMaterial color='#917251'/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,.01,0]} onPointerDown={onGround} receiveShadow><planeGeometry args={[26,21]}/><meshStandardMaterial map={turf} color='#bdcc91' roughness={1}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,.035,-1]} onPointerDown={onGround} receiveShadow><planeGeometry args={[23,2.2]}/><meshStandardMaterial color='#d2bd94'/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[1,.04,0]} onPointerDown={onGround} receiveShadow><planeGeometry args={[2.1,17]}/><meshStandardMaterial color='#d2bd94'/></mesh>
 <Model name='seed-cottage' position={[-6,0,-4]} scale={2}/><Model name='seed-cottage' position={[5,0,-4]} scale={2.4}/><Model name='seed-cottage' position={[8,0,4]} scale={1.5}/>
 {props.map(p=><Sprite key={p.id} url={`/images/charmville/workshop/${p.kind}@3x.png`} position={[p.x,1.5,p.z]} width={3.8} height={2.85}/>)}
 <Model name='flower-border' position={[-4,0,-2]} scale={1.7}/><Model name='flower-border' position={[5,0,-2]} scale={1.7}/>
 {GRASS.filter(g=>!cut.has(g.id)).map(g=><group key={g.id} position={[g.x,0,g.z]}>{[0,1,2].map(i=><mesh key={i} position={[(i-1)*.11,.25,0]} rotation={[.1,i*.7,(i-1)*.3]}><coneGeometry args={[.1,.55,3]}/><meshStandardMaterial color={i===1?'#93b55c':'#668c45'} side={THREE.DoubleSide}/></mesh>)}</group>)}
 <Html position={[-6,3,-4]} center><span className={styles.label}>SEEDKEEPER’S COTTAGE</span></Html><Html position={[5,3.4,-4]} center><button onClick={onAtlas}>Charm atlas ↗</button></Html><Html position={[8,2.6,4]} center><span className={styles.label}>CREATOR’S LODGE</span></Html>
 </>;
}
export default function World({active,onAtlas}:{active:boolean;onAtlas:()=>void}){
 const [cinema,setCinema]=useState(false);const [ufo,setUfo]=useState(false);const [attack,setAttack]=useState(0);const [cut,setCut]=useState<Set<number>>(new Set());const [props,setProps]=useState<Prop[]>(INITIAL);const [placing,setPlacing]=useState(false);const [notice,setNotice]=useState('Click the ground to walk. WASD / arrows move. Space swings your sword.');const [position,setPosition]=useState({x:0,z:0});const keys=useRef(new Set<string>());const location=useRef(new THREE.Vector3(0,0,0));const target=useRef(new THREE.Vector3(0,0,0));const cooldown=useRef(0);const frame=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(STORE);if(raw){const value=JSON.parse(raw);if(Array.isArray(value)&&value.length<=80&&value.every(p=>Number.isInteger(p.id)&&['orchard-tree','blossom-tree'].includes(p.kind)&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&Math.abs(p.x)<=12&&Math.abs(p.z)<=9)){// eslint-disable-next-line react-hooks/set-state-in-effect
 setProps(value);}}}catch{/* Corrupt draft leaves default world usable. */}},[]);
 function swing(){if(performance.now()-cooldown.current<380)return;cooldown.current=performance.now();setAttack(n=>n+1);const found=GRASS.filter(g=>Math.hypot(g.x-location.current.x,g.z-location.current.z)<1.8);setCut(current=>new Set([...current,...found.map(g=>g.id)]));setNotice(found.length?'Sword sweep · nearby grass cleared. Preview cuttings stay in this visit.':'Sword sweep · move into the meadow to cut grass.');}
 const swingRef=useRef(swing);useEffect(()=>{swingRef.current=swing;});
 useEffect(()=>{const element=frame.current;if(!element)return;const down=(e:KeyboardEvent)=>{if(!active||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLButtonElement)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase())){e.preventDefault();keys.current.add(e.key.toLowerCase());if(e.key===' '&&!e.repeat)swingRef.current();}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const clear=()=>keys.current.clear();element.addEventListener('keydown',down);element.addEventListener('keyup',up);element.addEventListener('blur',clear,true);window.addEventListener('blur',clear);return()=>{element.removeEventListener('keydown',down);element.removeEventListener('keyup',up);element.removeEventListener('blur',clear,true);window.removeEventListener('blur',clear);clear();};},[active]);
 function ground(e:ThreeEvent<PointerEvent>){e.stopPropagation();frame.current?.focus({preventScroll:true});if(placing){setProps(current=>current.length>=80?current:[...current,{id:Math.max(0,...current.map(p=>p.id))+1,kind:'blossom-tree',x:Math.round(e.point.x),z:Math.round(e.point.z)}]);setNotice('Blossom placed in your draft. Save scenery to keep it on this device.');}else target.current.set(e.point.x,0,e.point.z);}
 function save(){try{localStorage.setItem(STORE,JSON.stringify(props));setNotice('Scenery saved on this device. It has not been published to other players.');}catch{setNotice('This browser could not save your draft.');}}
 return <div ref={frame} tabIndex={0} className={styles.world} aria-label='Playable Charmville district'>
 <Canvas orthographic shadows dpr={[1,1.5]} frameloop={active?'always':'never'} camera={{position:[18,26,25],zoom:30,near:.1,far:200}} gl={{antialias:true}}><color attach='background' args={['#9ebeb4']}/><fog attach='fog' args={['#9ebeb4',45,90]}/><ambientLight intensity={1.1}/><hemisphereLight args={['#fff2d5','#53754e',1.5]}/><directionalLight position={[-10,18,8]} intensity={2.3} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-18} shadow-camera-right={18} shadow-camera-top={18} shadow-camera-bottom={-18} shadow-bias={-.0004}/><Camera cinema={cinema} player={location}/><Suspense fallback={null}><Terrain onGround={ground} cut={cut} props={props} onAtlas={onAtlas}/><Explorer target={target.current} attack={attack} keys={keys} location={location} onPosition={(x,z)=>setPosition({x,z})}/></Suspense><Visitor enabled={ufo}/></Canvas>
 <div className={styles.hud}><strong>Willow Commons</strong><small>Meadow cuttings {cut.size} / {GRASS.length} · Solo preview</small><small>Position {position.x.toFixed(1)}, {position.z.toFixed(1)}</small></div>
 <div className={styles.worldControls}><button aria-pressed={cinema} onClick={()=>setCinema(v=>!v)}>{cinema?'Return to 2.5D':'Reveal 3D'}</button><button aria-pressed={ufo} onClick={()=>{setUfo(v=>!v);setCinema(true);}}>UFO visual event</button><button aria-pressed={placing} onClick={()=>setPlacing(v=>!v)}>{placing?'Finish placing':'Place blossom'}</button><button onClick={save}>Save scenery</button><button onClick={()=>{setProps(INITIAL);setCut(new Set());setNotice('Preview reset. Save scenery to replace your stored draft.');}}>Reset preview</button></div>
 <div className={styles.help}><p aria-live='polite'>{notice}</p><button onClick={swing}>Swing sword</button></div>
 </div>;
}
