import { eq } from "drizzle-orm";
import { getDb } from "../../db";
import { xAccounts } from "../../db/schema";
import { decryptXCredential, encryptXCredential } from "./crypto";
import type { XAccount } from "./provider";

type CredentialRecord={accessTokenEncrypted:string;refreshTokenEncrypted:string};
type FetchLike=(input:string|URL,init?:RequestInit)=>Promise<Response>;
export function isUsableXAccountRecord(record:CredentialRecord,mode=process.env.PLANKSPACE_X_PROVIDER||"live"){return mode==="development"||Boolean(record.accessTokenEncrypted)}

export async function refreshXAccessToken({refreshToken,clientId,clientSecret,fetchImpl=fetch}:{refreshToken:string;clientId:string;clientSecret?:string;fetchImpl?:FetchLike}):Promise<{accessToken:string;refreshToken:string;expiresIn:number}>{if(!refreshToken||!clientId)throw new Error("Reconnect X to renew authorization");const form=new URLSearchParams({refresh_token:refreshToken,grant_type:"refresh_token",client_id:clientId}),headers:Record<string,string>={"content-type":"application/x-www-form-urlencoded"};if(clientSecret)headers.authorization=`Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`;const response=await fetchImpl("https://api.x.com/2/oauth2/token",{method:"POST",headers,body:form}),text=await response.text();let body:{access_token?:string;refresh_token?:string;expires_in?:number}={};try{body=text?JSON.parse(text):{}}catch{}if(!response.ok||!body.access_token)throw new Error(`Reconnect X to renew authorization (${response.status})`);return{accessToken:body.access_token,refreshToken:body.refresh_token||refreshToken,expiresIn:body.expires_in||7200}}

export function publicXAccount(row:typeof xAccounts.$inferSelect){return{connected:true,username:row.xUsername,userId:row.xUserId,connectedAt:row.connectedAt,provider:process.env.PLANKSPACE_X_PROVIDER==="development"?"development":"live"}}

export async function loadXAccount(wallet:string):Promise<XAccount|null>{const db=getDb(),[row]=await db.select().from(xAccounts).where(eq(xAccounts.wallet,wallet)).limit(1);if(!row||!isUsableXAccountRecord(row))return null;if(process.env.PLANKSPACE_X_PROVIDER==="development")return{id:row.xUserId,username:row.xUsername,accessToken:`development-${row.xUsername}`};let accessToken:string,refreshToken="";try{accessToken=decryptXCredential(row.accessTokenEncrypted);refreshToken=row.refreshTokenEncrypted?decryptXCredential(row.refreshTokenEncrypted):""}catch{return null}const expiresAt=row.tokenExpiresAt?Date.parse(row.tokenExpiresAt):Number.POSITIVE_INFINITY;if(expiresAt<=Date.now()+60_000){const refreshed=await refreshXAccessToken({refreshToken,clientId:process.env.X_CLIENT_ID||"",clientSecret:process.env.X_CLIENT_SECRET}),nextExpiry=new Date(Date.now()+refreshed.expiresIn*1000).toISOString();accessToken=refreshed.accessToken;refreshToken=refreshed.refreshToken;await db.update(xAccounts).set({accessTokenEncrypted:encryptXCredential(accessToken),refreshTokenEncrypted:encryptXCredential(refreshToken),tokenExpiresAt:nextExpiry,updatedAt:new Date().toISOString()}).where(eq(xAccounts.wallet,wallet));return{id:row.xUserId,username:row.xUsername,accessToken,refreshToken,expiresAt:nextExpiry}}return{id:row.xUserId,username:row.xUsername,accessToken,refreshToken:refreshToken||undefined,expiresAt:row.tokenExpiresAt||undefined}}
