"use client";
import { useCallback,useEffect,useState } from "react";
import { walletProof } from "../auth-client";

type Status={connected:boolean;needsReconnect?:boolean;username?:string;provider?:string;cooldownMinutes?:number;importWindow?:{allowed:boolean;retryAfterSeconds:number}};
async function readJson(response:Response){const text=await response.text();if(!text)return{};try{return JSON.parse(text)}catch{return{error:`PlankSpace received an unreadable response (${response.status}). Please try again.`}}}
function waitLabel(seconds:number){const hours=Math.ceil(seconds/3600);return hours<=1?"Available in under 1 hour":`Available in about ${hours} hours`}

export default function XConnectionManager({wallet,handle}:{wallet:string;handle:string}){const [status,setStatus]=useState<Status>({connected:false}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const refresh=useCallback(()=>fetch(`/api/x/status?handle=${handle}`).then(readJson).then(setStatus).catch(()=>setStatus({connected:false})),[handle]);useEffect(()=>{if(handle)void refresh()},[handle,refresh]);const act=async(action:"connect"|"disconnect"|"sync")=>{setBusy(true);setMessage("");try{const data={handle},proof=await walletProof(wallet,`x:${action}`,handle,data),response=await fetch(`/api/x/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}),body=await readJson(response);if(!response.ok)throw new Error(body.error||`X ${action} failed`);if(body.authorizationUrl){window.location.href=body.authorizationUrl;return}setMessage(action==="sync"?`Imported ${body.imported} new X post${body.imported===1?"":"s"}.`:action==="connect"?"X connected to this PlankSpace profile.":"X disconnected.");await refresh()}catch(error){setMessage(error instanceof Error?error.message:`X ${action} failed`)}finally{setBusy(false)}};const isDemo=status.provider==="development",importReady=status.importWindow?.allowed!==false;return <section className="x-connection-manager"><div className="x-connection-heading"><div><h2>Connect X</h2><p>Bring up to 20 recent X posts into the Lumberyard once per day. Cross-posting is optional and waits {status.cooldownMinutes??5} minutes between X posts.</p></div><span className={isDemo?"is-demo":"is-live"}>{isDemo?"Demo mode":"Live OAuth"}</span></div>{status.connected?<><p className="x-connection-status"><b>{isDemo?"Demo profile":"Connected X account"}</b><span>@{status.username}</span>{isDemo&&<small>This local account is not authenticated with X.</small>}{!importReady&&status.importWindow&&<small>{waitLabel(status.importWindow.retryAfterSeconds)}.</small>}</p><div className="x-connection-actions"><button type="button" disabled={busy||!importReady} onClick={()=>act("sync")}>{importReady?"Import latest 20 posts":"Import used today"}</button><button className="is-secondary" type="button" disabled={busy} onClick={()=>act("disconnect")}>Disconnect</button></div></>:<><p className="x-connection-status"><b>{status.needsReconnect?"Reconnect required":"X is optional"}</b><span>{status.needsReconnect?"The previous Demo connection cannot access live X.":"Connect your own X account when you are ready."}</span></p><button type="button" disabled={busy||!wallet||!handle} onClick={()=>act("connect")}>{status.needsReconnect?"Reconnect X":"Connect X to this profile"}</button></>}{message&&<p className="x-connection-message" role="status">{message}</p>}</section>}
