import { and, desc, eq, gt } from "drizzle-orm";
import { getDb } from "../../../db";
import { liveRoomMembers, liveRooms, profiles } from "../../../db/schema";
import { hashJson } from "../auth/hash";
import { type Proof, verifyAndConsumeProof } from "../auth/verify";

const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,48);
const text=(v:unknown,n:number)=>typeof v==="string"?v.trim().slice(0,n):"";
async function identity(wallet:string){const [p]=await getDb().select({handle:profiles.handle,displayName:profiles.displayName,avatarUrl:profiles.avatarUrl}).from(profiles).where(and(eq(profiles.wallet,wallet),eq(profiles.moderationStatus,"approved"))).limit(1);return p}

export async function GET(request:Request){const url=new URL(request.url),room=slug(url.searchParams.get("room")||""),publicRoom=(item:typeof liveRooms.$inferSelect)=>({id:item.id,slug:item.slug,title:item.title,description:item.description,hostHandle:item.hostHandle,status:item.status,jitsiRoom:item.jitsiRoom,createdAt:item.createdAt,updatedAt:item.updatedAt});const db=getDb();if(!room){const rows=await db.select().from(liveRooms).where(eq(liveRooms.status,"live")).orderBy(desc(liveRooms.updatedAt)).limit(50);const counts=await Promise.all(rows.map(async r=>(await db.select().from(liveRoomMembers).where(and(eq(liveRoomMembers.roomSlug,r.slug),eq(liveRoomMembers.removed,false),gt(liveRoomMembers.lastSeenAt,new Date(Date.now()-90000).toISOString())))).length));return Response.json({rooms:rows.map((r,i)=>({...publicRoom(r),participantCount:counts[i]}))})}const [item]=await db.select().from(liveRooms).where(eq(liveRooms.slug,room)).limit(1);if(!item)return Response.json({error:"Lounge not found"},{status:404});const members=await db.select({id:liveRoomMembers.id,handle:liveRoomMembers.handle,role:liveRoomMembers.role,micStatus:liveRoomMembers.micStatus,requestedMic:liveRoomMembers.requestedMic,removed:liveRoomMembers.removed}).from(liveRoomMembers).where(and(eq(liveRoomMembers.roomSlug,room),gt(liveRoomMembers.lastSeenAt,new Date(Date.now()-90000).toISOString()))).orderBy(desc(liveRoomMembers.role));return Response.json({room:publicRoom(item),members})}

export async function POST(request:Request){
 const payload=await request.json() as Proof&{action?:string;room?:string;title?:string;description?:string;targetMemberId?:number;micStatus?:string},action=text(payload.action,30),room=slug(payload.room||payload.title||""),data={action,room,title:text(payload.title,80),description:text(payload.description,240),targetMemberId:Math.max(0,Number(payload.targetMemberId)||0),micStatus:payload.micStatus==="unmuted"?"unmuted":"muted"},hash=await hashJson(data),wallet=await verifyAndConsumeProof(payload,"live-room:act",room,hash);
 if(!wallet)return Response.json({error:"Signed PlankSpace session required"},{status:403});const db=getDb(),me=await identity(wallet);if(!me)return Response.json({error:"An approved profile is required"},{status:403});
 if(action==="create"){if(!room)return Response.json({error:"A lounge title is required"},{status:400});const [existing]=await db.select().from(liveRooms).where(eq(liveRooms.slug,room)).limit(1);if(existing&&existing.status==="live")return Response.json({error:"That lounge name is already live"},{status:409});const jitsiRoom=`plankspace-${room}-${crypto.randomUUID().slice(0,8)}`;await db.insert(liveRooms).values({slug:room,title:data.title||room,description:data.description,hostWallet:wallet,hostHandle:me.handle,jitsiRoom}).onConflictDoUpdate({target:liveRooms.slug,set:{title:data.title||room,description:data.description,hostWallet:wallet,hostHandle:me.handle,status:"live",jitsiRoom,updatedAt:new Date().toISOString()}});await db.insert(liveRoomMembers).values({roomSlug:room,wallet,handle:me.handle,role:"host",micStatus:"muted"}).onConflictDoUpdate({target:[liveRoomMembers.roomSlug,liveRoomMembers.wallet],set:{role:"host",removed:false,lastSeenAt:new Date().toISOString()}});return Response.json({room})}
 const [item]=await db.select().from(liveRooms).where(eq(liveRooms.slug,room)).limit(1);if(!item||item.status!=="live")return Response.json({error:"That lounge is not live"},{status:404});
 if(action==="join"||action==="heartbeat"){const [prior]=await db.select().from(liveRoomMembers).where(and(eq(liveRoomMembers.roomSlug,room),eq(liveRoomMembers.wallet,wallet))).limit(1);if(prior?.removed)return Response.json({error:"The host removed you from this lounge"},{status:403});const role=wallet===item.hostWallet?"host":prior?.role||"listener";await db.insert(liveRoomMembers).values({roomSlug:room,wallet,handle:me.handle,role}).onConflictDoUpdate({target:[liveRoomMembers.roomSlug,liveRoomMembers.wallet],set:{handle:me.handle,lastSeenAt:new Date().toISOString()}});const [saved]=await db.select({id:liveRoomMembers.id}).from(liveRoomMembers).where(and(eq(liveRoomMembers.roomSlug,room),eq(liveRoomMembers.wallet,wallet))).limit(1);return Response.json({room:{...item,hostWallet:undefined},member:{id:saved.id,handle:me.handle,displayName:me.displayName,avatarUrl:me.avatarUrl?`/api/avatar?handle=${me.handle}`:"",role}})}
 const [member]=await db.select().from(liveRoomMembers).where(and(eq(liveRoomMembers.roomSlug,room),eq(liveRoomMembers.wallet,wallet))).limit(1);if(!member||member.removed)return Response.json({error:"Join the lounge first"},{status:403});
 if(action==="request-mic"){await db.update(liveRoomMembers).set({requestedMic:true,lastSeenAt:new Date().toISOString()}).where(and(eq(liveRoomMembers.roomSlug,room),eq(liveRoomMembers.wallet,wallet)));return Response.json({ok:true})}
 if(action==="mic-status"&&(member.role==="host"||member.role==="speaker")){await db.update(liveRoomMembers).set({micStatus:data.micStatus,lastSeenAt:new Date().toISOString()}).where(and(eq(liveRoomMembers.roomSlug,room),eq(liveRoomMembers.wallet,wallet)));return Response.json({ok:true})}
 if(wallet!==item.hostWallet)return Response.json({error:"Only the host may moderate this lounge"},{status:403});
 if(action==="close"){await db.update(liveRooms).set({status:"ended",updatedAt:new Date().toISOString()}).where(eq(liveRooms.slug,room));return Response.json({ok:true})}
 if(!data.targetMemberId)return Response.json({error:"A valid participant is required"},{status:400});const target=and(eq(liveRoomMembers.roomSlug,room),eq(liveRoomMembers.id,data.targetMemberId));
 if(action==="promote")await db.update(liveRoomMembers).set({role:"speaker",requestedMic:false,micStatus:"muted"}).where(target);
 else if(action==="demote")await db.update(liveRoomMembers).set({role:"listener",requestedMic:false,micStatus:"muted"}).where(target);
 else if(action==="mute")await db.update(liveRoomMembers).set({micStatus:"muted"}).where(target);
 else if(action==="remove")await db.update(liveRoomMembers).set({removed:true,micStatus:"muted"}).where(target);
 else return Response.json({error:"Unsupported lounge action"},{status:400});return Response.json({ok:true});
}
