"use client";
/* eslint-disable @next/next/no-img-element, @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { useEffect,useMemo,useState } from "react";import { parseEther } from "ethers";import { getPlankLoveWalletState,sendPlankLoveNativeTransaction } from "../plank-love-wallet";import { safeChartUrl } from "./widget-safety";import type { ProfileWidget } from "./widget-types";import ExternalWidgetFrame from "./external-widget-frame";
function short(value:string){return value.length>18?`${value.slice(0,8)}…${value.slice(-6)}`:value}
function TokenMarket({contract}:{contract:string}){const [market,setMarket]=useState<{priceUsd?:string;change24h?:number}|null>(null);useEffect(()=>{if(contract)void fetch(`/api/widget-market?token=${encodeURIComponent(contract)}`).then(r=>r.json()).then(x=>setMarket(x.market||null)).catch(()=>undefined)},[contract]);if(!market)return <small>Live price unavailable</small>;return <small>${market.priceUsd||"—"} · 24h {Number(market.change24h||0).toFixed(2)}%</small>}
function TipJar({handle,config}:{handle:string;config:Record<string,unknown>}){
 const presets=Array.isArray(config.presets)?config.presets.map(String):[],recipient=String(config.recipient||""),token=String(config.tokenSymbol||"NATIVE"),chainId=Number(config.chainId||0),[amount,setAmount]=useState(presets[0]||""),[publicSender,setPublic]=useState(true),[message,setMessage]=useState(""),[tips,setTips]=useState<Array<{id:number;sender:string;amount:string;tokenSymbol:string}>>([]);const load=()=>fetch(`/api/tips?handle=${encodeURIComponent(handle)}`).then(r=>r.json()).then(x=>setTips(x.tips||[])).catch(()=>undefined);useEffect(()=>{if(config.showRecent!==false)void load()},[handle,config.showRecent]);
 const send=async()=>{setMessage("");try{if(!/^\d+(?:\.\d{1,18})?$/.test(amount)||Number(amount)<=0)throw new Error("Enter a valid amount.");const state=await getPlankLoveWalletState();if(!state.address||!state.isConnected)throw new Error("Connect your Plank.love wallet first.");if(state.chainId!==chainId)throw new Error(`Switch your wallet to ${String(config.chainLabel||`chain ${chainId}`)} before continuing.`);if(!confirm(`Toss ${amount} ${token}\nTo: ${recipient}\nNetwork: ${String(config.chainLabel||chainId)}\n\nYour wallet will show the final transaction for confirmation.`))return;const txHash=await sendPlankLoveNativeTransaction({address:state.address,to:recipient,valueHex:`0x${parseEther(amount).toString(16)}`,chainId});setMessage(`Transaction sent: ${short(txHash)}. Waiting for confirmation…`);for(let i=0;i<18;i++){await new Promise(r=>setTimeout(r,4000));const response=await fetch("/api/tips",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({handle,senderWallet:state.address,txHash,publicSender})}),body=await response.json();if(response.ok){setMessage(`Verified: ${body.amount} ${token} tossed!`);void load();return}if(response.status!==422)throw new Error(body.error||"Tip verification failed")}throw new Error("The transaction is still pending. It can be verified after confirmation.")}catch(e){setMessage(e instanceof Error?e.message:"Tip failed")}};
 return <div className="tip-jar-body"><div className="tip-presets">{presets.map(x=><button key={x} type="button" onClick={()=>setAmount(x)}>{x}</button>)}</div><label>Amount ({token})<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><input type="checkbox" checked={publicSender} onChange={e=>setPublic(e.target.checked)}/> Show my name publicly</label><button type="button" onClick={send}>Toss a Chip</button><small>Direct to {short(recipient)}. PlankSpace never takes custody.</small>{message&&<p role="status">{message}</p>}{config.showRecent!==false&&tips.length>0&&<ul className="recent-chips">{tips.map(t=><li key={t.id}><b>{t.sender}</b> tossed {t.amount} {t.tokenSymbol}</li>)}</ul>}</div>;
}
function WidgetBody({widget,handle}:{widget:ProfileWidget;handle:string}){
 const c=widget.config;
 if(widget.type==="wallet")return <ul className="public-wallets">{(Array.isArray(c.addresses)?c.addresses:[]).map((x:any,i)=><li key={i}><span>{x.chain||"Wallet"}{x.label?` · ${x.label}`:""}</span><code>{short(String(x.address))}</code><button type="button" onClick={()=>navigator.clipboard.writeText(String(x.address))}>Copy</button></li>)}</ul>;
 if(widget.type==="favorite-token")return <div className="favorite-token">{Boolean(c.logoUrl)&&<img src={String(c.logoUrl)} alt=""/>}<div><b>{String(c.name||"Favorite Token")} <small>${String(c.symbol||"")}</small></b><span>{String(c.chain||"")} · {short(String(c.contract||""))}</span><TokenMarket contract={String(c.contract||"")}/>{Boolean(c.message)&&<p>{String(c.message)}</p>}</div></div>;
 if(widget.type==="token-chart"){const src=safeChartUrl(c.url);return src?<iframe className="token-chart-frame" src={src} title={widget.title} loading="lazy" sandbox="allow-scripts allow-same-origin" referrerPolicy="no-referrer"/>:<p>Add a valid DexScreener or DEXTools chart URL.</p>}
 if(widget.type==="portfolio"){const mode=String(c.mode||"hidden"),assets=Array.isArray(c.assets)?c.assets:[];if(mode==="hidden")return <p>This portfolio is private.</p>;return <ul className="portfolio-assets">{assets.map((a:any,i)=><li key={i}><b>{a.symbol}</b><span>{a.name}</span>{mode==="allocation"&&<em>{a.allocation}%</em>}{mode==="full"&&<em>{a.amount} · {a.value}</em>}</li>)}</ul>}
 if(widget.type==="tip-jar")return <TipJar handle={handle} config={c}/>;
 if(widget.type==="custom")return <ExternalWidgetFrame title={widget.title} source={String(c.source||c.html||"")} origins={Array.isArray(c.origins)?c.origins.map(String):[]} css={String(c.css||"")}/>;return null;
}
export default function ProfileWidgets({handle}:{handle:string}){const [widgets,setWidgets]=useState<ProfileWidget[]>([]);useEffect(()=>{void fetch(`/api/widgets?handle=${encodeURIComponent(handle)}`).then(r=>r.json()).then(x=>setWidgets(x.widgets||[])).catch(()=>undefined)},[handle]);const ordered=useMemo(()=>[...widgets].sort((a,b)=>a.sortOrder-b.sortOrder),[widgets]);if(!ordered.length)return null;return <section className="profile-widgets" id="profile-widgets" data-profile-module="widgets"><div className="head"><h2>Widgets</h2><span>Owner-curated modules</span></div>{ordered.map(widget=><article key={String(widget.id)} id={`profile-widget-${widget.id}`} data-widget-id={widget.id} data-widget-type={widget.type} className={`profile-widget widget-${widget.type} ${widget.desktopVisible?"":"widget-hide-desktop"} ${widget.mobileVisible?"":"widget-hide-mobile"}`} style={{"--widget-bg":widget.style.background,"--widget-opacity":widget.style.opacity,"--widget-border":widget.style.borderColor,"--widget-border-width":`${widget.style.borderWidth}px`,"--widget-radius":`${widget.style.borderRadius}px`} as React.CSSProperties}><h3>{widget.title}</h3><WidgetBody widget={widget} handle={handle}/></article>)}</section>}
