import test from "node:test";
import assert from "node:assert/strict";
import { customProfileCss, hasVisibleCustomContent } from "../app/custom-profile-css";

test("applies MySpace layout CSS to the full profile",()=>{const css=customProfileCss('<style>body{background:#111;color:white;font-family:Georgia}.content,.box{border:3px double orange}a{color:lime}</style>');assert.match(css,/\.classic-profile\[class\] \{background:#111!important;color:white!important;font-family:Georgia!important\}/);assert.match(css,/\.classic-profile \.content,\.classic-profile \.box/);assert.match(css,/\.classic-profile a \{color:lime!important\}/)});
test("blocks executable CSS and layout-breaking properties",()=>{const css=customProfileCss('<style>body{background:url(javascript:alert(1));position:fixed;width:9999px;color:red}</style>');assert.equal(css,'.classic-profile[class] {color:red!important}')});
test("translates legacy MySpace table selectors, bare colors, and HTTP art",()=>{const css=customProfileCss('<style>table table td{background-color:000000}.profileInfo{border:C90000 2px solid}body{background:url(http://www.fillster.com/images/backgrounds/176z.gif)}</style>');assert.match(css,/background-color:#000000!important/);assert.match(css,/\.classic-profile \.identity \{border:#C90000 2px solid!important\}/);assert.match(css,/url\(https:\/\/www\.fillster\.com/)});
test("safely preserves CRT overlays and image filters",()=>{const css=customProfileCss('<style>body::before{background:linear-gradient(transparent 50%,#0004 50%);background-size:100% 2px;position:fixed;pointer-events:none}img{filter:sepia(100%) hue-rotate(45deg) saturate(5)}</style>');assert.match(css,/\.classic-profile::before/);assert.match(css,/position:absolute!important/);assert.match(css,/animation:plankspace-crt-flicker/);assert.match(css,/\.classic-profile img \{filter:sepia\(100%\) hue-rotate\(45deg\) saturate\(5\)!important\}/)});
test("distinguishes CSS-only layouts from visible custom content",()=>{assert.equal(hasVisibleCustomContent('<style>body{background:black}</style>'),false);assert.equal(hasVisibleCustomContent('<style>body{color:lime}</style><h2>Welcome</h2>'),true);assert.equal(hasVisibleCustomContent('<img src="data:image/png;base64,abc">'),true)});
