import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { createPageMetadata } from "@/lib/seo";
import {
  LegalClause,
  LegalH2,
  LegalH3,
  LegalHeader,
  LegalNote,
  LegalUl,
} from "@/components/legal/LegalProse";

export const metadata = createPageMetadata({
  title: "Terms",
  description:
    "The plain-language terms for using plank.love: risk, no promised return, self-custody, user submissions, and third-party services.",
  path: "/terms",
  keywords: ["RobinWood terms", "$PLANK terms of use"],
});

const LAST_UPDATED = "August 2, 2026";

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main id="main-content" tabIndex={-1} className="flex-1 px-3 py-10 sm:px-5">
        <article className="wood-ledger mx-auto w-full max-w-3xl space-y-1 rounded-2xl p-5 sm:p-8">
          <LegalHeader
            eyebrow="The fine print"
            title="Terms of Use"
            dek="Read this before you touch anything gold-colored. It&apos;s a meme project with a real wallet attached, so the jokes stop where the money starts."
            lastUpdated={LAST_UPDATED}
          />

          <LegalH2 id="what-this-is">1. What RobinWood is (and isn&apos;t)</LegalH2>
          <LegalClause>
            RobinWood, $PLANK, and every surface of plank.love (mint, Trade, Marketplank,
            Instant Swap, the Gallery, Memes, and everything else on this domain) are a meme
            project. There is no promised return, no guaranteed price, and no expectation of
            profit attached to holding, trading, minting, or providing liquidity for anything
            here.
          </LegalClause>
          <LegalClause>
            Nothing on this site is financial advice, investment advice, legal advice, or tax
            advice, and nothing here is an offer or solicitation to buy or sell a security. Do
            your own research. If you need advice, get it from a licensed professional, not from
            a cartoon plank.
          </LegalClause>

          <LegalH2 id="nft-ownership">2. What owning a Plank NFT means (and doesn&apos;t)</LegalH2>
          <LegalClause>
            A RobinWood NFT is a token recorded on Robinhood Chain. Owning one means you control
            that token in your wallet and whatever the associated art, metadata, and any
            explicitly stated on-chain utility give you — nothing more.
          </LegalClause>
          <LegalUl
            items={[
              "It is not equity, a security, a partnership interest, or any other ownership stake in RobinWood, plank.love, or anyone who operates it.",
              "It does not entitle you to a share of revenue, fees, royalties, or profits generated by the project, by other holders, or by anyone else's efforts.",
              "It does not create an expectation of profit from the managerial or entrepreneurial efforts of us or any third party — if you acquire one hoping its value rises because of what we build or do, that hope is not a promise and is not something we guarantee.",
              "Its price, if any exists on a marketplace or in a vault, is set by other market participants and by automated contract logic, not by us.",
            ]}
          />

          <LegalH2 id="smart-contracts">3. Smart contracts don&apos;t get a redo</LegalH2>
          <LegalClause>
            The RobinWood NFT contract, the $PLANK token, Seaport (Marketplank&apos;s order
            protocol), and every Instant Swap vault are on-chain smart contracts. They are
            <strong> immutable</strong> once deployed — nobody, including us, can quietly patch a
            bug after the fact — and they have <strong>not been audited by an independent
            third-party security firm</strong>. Code that looks fine can still contain a bug or
            an exploit that neither we nor you can undo.
          </LegalClause>
          <LegalClause>
            Every transaction you sign on this site — a mint, a swap, a listing, an offer, a
            deposit, a redemption — is <strong>irreversible</strong> once it confirms on chain.
            There is no support ticket that reverses a transaction. You are solely responsible
            for your own wallet, private keys, and seed phrase; we never have access to them and
            cannot recover them for you.
          </LegalClause>
          <LegalNote>
            Total loss is a real possible outcome, not a disclaimer for show. Only ever risk what
            you can afford to lose completely.
          </LegalNote>

          <LegalH2 id="no-custody">4. We don&apos;t hold your wood (or your funds)</LegalH2>
          <LegalClause>
            plank.love is non-custodial. We do not hold, control, or have access to your ETH,
            $PLANK, NFTs, or LP position at any point. Marketplank orders are signed by your
            wallet and only ever executed by contracts you approve; Instant Swap deposits and
            redemptions move directly between your wallet and the vault contract. If a vault, the
            token contract, or your own wallet is compromised, we cannot reach in and make you
            whole.
          </LegalClause>

          <LegalH2 id="vaults">5. Instant Swap and the vaults</LegalH2>
          <LegalClause>
            Instant Swap lets you deposit a RobinWood NFT into a vault contract for $PLANK, or
            spend $PLANK to pull an NFT back out. Every vault is an automated, immutable smart
            contract — pricing, fees, and eligibility are set by contract logic, not by a person
            deciding in real time, and nobody (including us) can pause a single trade or reverse
            one after it confirms.
          </LegalClause>
          <LegalUl
            items={[
              "We do not guarantee that a vault will hold liquidity, that a swap will fill at any particular price, or that any particular token will be available to redeem at any given time.",
              "A vault can hold zero NFTs, zero $PLANK, or be otherwise unable to fill your swap. That is normal contract behavior, not a malfunction.",
              "Retiring vaults (older versions kept live after a newer one launches) exist for exit only — to let existing holders withdraw or redeem their position. Depositing new value into a retiring vault is not the intended use, and we may restrict or discourage it in the interface.",
              "Multiple vault versions can be live at once. The version you are interacting with is always shown by product name in the interface, and the interface will not let you send a transaction to a vault we have not verified as safe to use.",
            ]}
          />
          <LegalH3>Random redeem</LegalH3>
          <LegalClause>
            Some vaults let you request a random NFT instead of choosing a specific one. The
            random outcome is generated using an external public randomness beacon (a drand
            network), not a value we or any single party control or can predict in advance. Once
            the beacon publishes the round used for your request, the contract deterministically
            derives which held token you receive from it.
          </LegalClause>
          <LegalUl
            items={[
              "You are not guaranteed any particular token, tier, or rarity from a random redeem — the odds are simply each held token's share of the vault's pool at the moment your request settles.",
              "The randomness beacon is a third-party public network we do not operate. If it is delayed or unavailable, your request can sit pending until a round is relayed; this delay is a property of the beacon, not a right we are withholding.",
              "Choosing a specific held token (a targeted redeem) instead of a random one is a separate action with its own price set by contract logic, not a workaround for random-redeem odds.",
            ]}
          />

          <LegalH2 id="marketplace">6. Marketplank (the marketplace)</LegalH2>
          <LegalClause>
            Marketplank is a peer-to-peer marketplace built on the Seaport order protocol. Every
            listing and offer is an order signed by the user&apos;s own wallet; we store and
            display signed orders so other visitors can find and fulfill them, but we are not a
            party to any trade, we do not set prices, and we never take custody of the NFT, ETH,
            or $PLANK involved. A trade happens directly between the two wallets when one of them
            submits the matching transaction on chain.
          </LegalClause>
          <LegalClause>
            Because we are not a party to the trade, we cannot cancel, reverse, or guarantee the
            outcome of any listing or offer once it is signed or once it fills on chain. Verify
            what you are buying or selling — including the contract address, the token ID, and the
            price — before you sign anything.
          </LegalClause>

          <LegalH2 id="no-warranty">7. As-is, no warranty</LegalH2>
          <LegalClause>
            The site, the contracts, and everything on them are provided <strong>&quot;as
            is&quot;</strong> and <strong>&quot;as available,&quot;</strong> without warranty of
            any kind, express or implied — including, without limitation, any warranty of
            merchantability, fitness for a particular purpose, title, or non-infringement. We do
            not warrant that the site or any contract will be uninterrupted, error-free, or
            secure.
          </LegalClause>
          <LegalClause>
            To the fullest extent permitted by law, we disclaim liability for any loss arising
            from your use of the site, a smart contract, a third-party service linked from the
            site, or a bug, exploit, outage, or price movement — including total loss of funds.
          </LegalClause>

          <LegalH2 id="eligibility">8. Who can use this</LegalH2>
          <LegalUl
            items={[
              "You must be of legal age to enter into a binding contract where you live.",
              "You must not be located in, or a resident of, a country or region where using a site like this, or acquiring or trading a token or NFT like this, is prohibited by law or sanctions.",
              "You are responsible for knowing and following the law that applies to you — we don't and can't vet every visitor's jurisdiction.",
            ]}
          />

          <LegalH2 id="prohibited">9. Prohibited use</LegalH2>
          <LegalClause>You may not use plank.love, or ask anyone else to on your behalf, to:</LegalClause>
          <LegalUl
            items={[
              "Transact from, or route funds through, an address, entity, or jurisdiction subject to applicable sanctions, or otherwise evade sanctions or export-control law.",
              "Launder money, finance terrorism, or move proceeds of crime through mint, swap, redeem, or marketplace activity.",
              "Manipulate a market — wash trading, spoofing listings, or coordinating trades to move a vault's price or a token's apparent value artificially.",
              "Abuse the site's APIs or infrastructure: scraping or querying at a rate designed to degrade service for other users, attempting to bypass rate limits, or automating interactions with an intent to exploit contract logic rather than use it as intended.",
              "Attempt to gain unauthorized access to the site, the admin console, or any wallet, key, or account that is not yours.",
              "Upload or submit anything through the Memes page that violates the rules in Section 15 below.",
            ]}
          />
          <LegalClause>
            We may restrict, delay, or refuse to display activity connected to a prohibited use in
            the interface we control (for example, the marketplace listing feed), though we cannot
            reverse or prevent an on-chain transaction once it is broadcast, because the underlying
            contracts are permissionless.
          </LegalClause>

          <LegalH2 id="taxes">10. Taxes</LegalH2>
          <LegalClause>
            You are solely responsible for determining what taxes, if any, apply to your activity
            on plank.love — minting, trading, swapping, providing liquidity, redeeming, or
            receiving anything of value — and for reporting and paying them in your jurisdiction.
            We do not withhold, remit, or report taxes on your behalf, and nothing on this site is
            tax advice.
          </LegalClause>

          <LegalH2 id="gas">11. Gas, failed transactions &amp; chain reorgs</LegalH2>
          <LegalClause>
            Network gas fees are set by Robinhood Chain, not by us, and are non-refundable once
            paid — this applies whether your transaction succeeds, fails, or reverts. We are not
            responsible for a transaction that fails, is dropped, is front-run, or is reordered by
            the network, and we do not reimburse gas spent on a failed or reverted transaction. If
            the chain experiences a reorganization, the state your transaction confirmed against
            can change; we are not responsible for outcomes caused by a reorg.
          </LegalClause>

          <LegalH2 id="changes">12. Things may change or go away</LegalH2>
          <LegalClause>
            We may add, change, pause, or discontinue any feature of the site — Trade, Instant
            Swap, Marketplank, minting, WoodAmp, Memes, or anything else — at any time, with or
            without notice. Features described here or elsewhere on the site (fee rates, vault
            availability, supported chains) reflect how things work today and are not a promise
            of how they will work tomorrow.
          </LegalClause>

          <LegalH2 id="ip">13. Owning a Plank doesn&apos;t buy you the lumber yard</LegalH2>
          <LegalClause>
            Owning a RobinWood NFT does not, by itself, transfer any intellectual-property
            rights beyond what is expressly stated on this site. Specifically, ownership of an
            NFT does not grant you rights to the RobinWood brand, the plank character art, the
            RobinWood name or logo, or any trademark, except as separately and explicitly
            granted. The underlying artwork and metadata remain subject to the rights described
            for the collection; NFT ownership is ownership of the token, not an automatic license
            to everything associated with it.
          </LegalClause>

          <LegalH2 id="submissions">14. User submissions (Memes)</LegalH2>
          <LegalClause>
            The Memes page lets visitors submit images and video to the Community Meme Vault, a
            third-party service operated at <code className="rounded bg-black/30 px-1 py-0.5 text-[0.85em]">memes.smoothbrain.app</code>{" "}
            (not run by us). By submitting anything there, you represent, warrant, and agree to
            the following:
          </LegalClause>
          <LegalUl
            items={[
              "You own what you submit, or you hold every right needed to submit it and to grant the license below — this includes the underlying art, footage, music, and anyone's likeness that appears in it. Don't upload someone else's work or image without their permission.",
              "Your submission does not infringe any copyright, trademark, or other right, is not defamatory, and does not violate any law.",
              "By submitting, you grant us and the Community Meme Vault a non-exclusive, worldwide, royalty-free, sublicensable license to host, display, reproduce, and distribute your submission on plank.love, the Community Meme Vault, and related promotional surfaces (including social posts about the project). You keep ownership of what you submit — this is a license, not a transfer.",
              "You remain solely responsible for your submission; we are not responsible for content submitted by other users and we do not pre-screen every submission before it reaches the moderation queue.",
              "Moderation happens at the Community Meme Vault, a third party, not us. A submission may be rejected or removed at their discretion or ours, and nothing you submit is guaranteed to be published or to stay published.",
            ]}
          />
          <LegalClause>
            <strong>Report a submission or request removal:</strong> email{" "}
            <a href="mailto:abuse@plank.love" className="text-gold-300 underline underline-offset-2">
              abuse@plank.love
            </a>{" "}
            with a link to the asset (or its asset ID), the reason for the report — infringement,
            impersonation, illegal content, or anything else that violates this section — and, if
            you are the rights holder, a statement to that effect. Each meme card on the Memes page
            also has a direct &quot;Report&quot; link that prefills this for you.
          </LegalClause>

          <LegalH2 id="third-party">15. Third-party services we don&apos;t control</LegalH2>
          <LegalClause>
            plank.love links to, embeds, or depends on services we don&apos;t operate and can&apos;t
            control the uptime, accuracy, or policies of, including:
          </LegalClause>
          <LegalUl
            items={[
              "IPFS gateways (used to load NFT metadata and images)",
              "Blockscout (the block explorer for Robinhood Chain)",
              "OpenSea (referenced for order compatibility / discovery)",
              "Uniswap (quotes and swap routing on the Trade page)",
              "0x (used for certain swap routing)",
              "WalletConnect / Reown (wallet connection)",
              "The Community Meme Vault (memes.smoothbrain.app)",
              "A public drand randomness beacon (used to settle random redeems)",
            ]}
          />
          <LegalClause>
            Your use of any of these is subject to that service&apos;s own terms and privacy
            policy, and we are not responsible for their availability, content, or conduct.
          </LegalClause>

          <LegalH2 id="entity">16. Who &quot;we&quot; are</LegalH2>
          <LegalClause>
            plank.love is a community-operated project. There is no registered company, fund, or
            other legal entity behind it named in these Terms, and no such entity is a party to
            them. &quot;We,&quot; &quot;us,&quot; and &quot;the operators&quot; mean the people who
            build, deploy, and maintain plank.love and its contracts. We are not a bank, broker,
            exchange, money transmitter, or other regulated financial institution, and nothing
            here should be read as a claim that we are.
          </LegalClause>

          <LegalH2 id="disputes">17. Governing law &amp; disputes</LegalH2>
          <LegalClause>
            Because there is no registered operating entity behind plank.love (Section 16), these
            Terms do not name a single governing law or exclusive court. Instead, disputes are
            handled as follows.
          </LegalClause>
          <LegalH3>Step 1 — talk to us first</LegalH3>
          <LegalClause>
            Before filing any claim, contact{" "}
            <a href="mailto:legal@plank.love" className="text-gold-300 underline underline-offset-2">
              legal@plank.love
            </a>{" "}
            with a description of the dispute and what would resolve it. We will make a good-faith
            effort to respond within 30 days and to resolve the issue informally. Most
            disagreements about a transaction, a listing, or a submission can be sorted out at this
            stage without anyone needing a lawyer.
          </LegalClause>
          <LegalH3>Step 2 — your local courts and consumer rights apply</LegalH3>
          <LegalClause>
            If informal resolution doesn&apos;t work, any dispute may be brought in the courts of
            the country or state where you live, applying the law of that place. Nothing in these
            Terms removes, limits, or waives any consumer-protection right, statutory right, or
            other mandatory protection you have under the law of your own jurisdiction — where a
            clause in these Terms would conflict with a right you cannot waive under your local
            law, your local law controls for you, and the rest of these Terms remains in force.
          </LegalClause>
          <LegalH3>Severability</LegalH3>
          <LegalClause>
            If any provision of these Terms is found unenforceable by a court of competent
            jurisdiction, that provision is limited or removed to the minimum extent necessary, and
            the remaining provisions stay in full effect.
          </LegalClause>
          <LegalH2 id="contact">18. Contact</LegalH2>
          <LegalUl
            items={[
              <>
                <a href="mailto:legal@plank.love" className="text-gold-300 underline underline-offset-2">
                  legal@plank.love
                </a>{" "}
                — questions about these Terms, disputes, and general legal matters.
              </>,
              <>
                <a href="mailto:privacy@plank.love" className="text-gold-300 underline underline-offset-2">
                  privacy@plank.love
                </a>{" "}
                — data questions and requests (see our Privacy Policy).
              </>,
              <>
                <a href="mailto:abuse@plank.love" className="text-gold-300 underline underline-offset-2">
                  abuse@plank.love
                </a>{" "}
                — reporting a meme submission, an IP complaint, or other content issue.
              </>,
            ]}
          />

          <LegalClause>
            Related reading: our{" "}
            <Link href="/privacy" className="text-gold-300 underline underline-offset-2">
              Privacy Policy
            </Link>{" "}
            covers what data plank.love actually touches.
          </LegalClause>
        </article>
      </main>
      <Footer />
    </>
  );
}
