"use client";
import Link from "next/link";
/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages */
import {useState} from "react";
import {connectPlankLoveWallet} from "../plank-love-wallet";
import {walletProof} from "../auth-client";
type Profile={handle:string;displayName:string;bio:string;avatarUrl:string;mood:string};
type FriendRequest={id:number;requesterHandle:string;recipientHandle:string};
export default function PlanksListClient(){
 const [wallet,setWallet]=useState(""),[friends,setFriends]=useState<Profile[]>([]),[all,setAll]=useState<Profile[]>([]),[incoming,setIncoming]=useState<FriendRequest[]>([]),[outgoing,setOutgoing]=useState<FriendRequest[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const call=async(action:string,extra:Record<string,unknown>={})=>{const w=wallet||await connectPlankLoveWallet(),resource=action==="list"?"self":action==="respond"?String(extra.requestId):String(extra.targetHandle),data={action,...extra},proof=await walletProof(w,`friend:${action}`,resource,data),r=await fetch("/api/friends",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...proof,...data})}).then(x=>x.json());if(r.error)throw new Error(r.error);setWallet(w);return r};
 const load=async()=>{setBusy(true);setMessage("");try{const r=await call("list");setFriends(r.friends||[]);setAll(r.all||[]);setIncoming(r.incoming||[]);setOutgoing(r.outgoing||[])}catch(e){setMessage(e instanceof Error?e.message:"Could not open your Planks List")}finally{setBusy(false)}};
 const respond=async(id:number,decision:"accept"|"decline")=>{setBusy(true);try{await call("respond",{requestId:id,decision});await load()}catch(e){setMessage(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 const remove=async(handle:string)=>{if(!confirm(`Remove @${handle} from your friends?`))return;setBusy(true);try{await call("remove",{targetHandle:handle});await load()}catch(e){setMessage(e instanceof Error?e.message:"Remove failed")}finally{setBusy(false)}};
 const request=async(handle:string)=>{setBusy(true);try{await call("request",{targetHandle:handle});setMessage(`Friend request sent to @${handle}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 const pending=new Set(outgoing.map(x=>x.recipientHandle)),friendHandles=new Set(friends.map(x=>x.handle));
 return <div className="planks-shell"><header><Link className="brand" href="/plankspace">plank<span>space</span></Link><nav><a href="/plankspace">Home</a><a href="/browse">Browse</a><a href="/board-mail">Board Mail</a></nav></header><main><section className="planks-hero"><small>YOUR SOCIAL LUMBERYARD</small><h1>Planks List</h1><p>Every new board starts connected to DegenWaffle. Add fellow planks to build your own circle and connections feed.</p>{!wallet&&<button onClick={load} disabled={busy}>{busy?"Connecting…":"Connect & Open My Planks List"}</button>}{message&&<p role="status">{message}</p>}</section>{wallet&&<><section className="request-stack"><div><h2>Friend requests <b>{incoming.length}</b></h2>{incoming.map(x=><article key={x.id}><a href={`/u/${x.requesterHandle}`}>@{x.requesterHandle}</a><span><button disabled={busy} onClick={()=>respond(x.id,"accept")}>Accept</button><button disabled={busy} onClick={()=>respond(x.id,"decline")}>Decline</button></span></article>)}{!incoming.length&&<p>No requests waiting.</p>}</div><div><h2>Pending <b>{outgoing.length}</b></h2>{outgoing.map(x=><article key={x.id}><a href={`/u/${x.recipientHandle}`}>@{x.recipientHandle}</a><small>Request sent</small></article>)}{!outgoing.length&&<p>No outgoing requests.</p>}</div></section><section><h2>My Friends ({friends.length})</h2><div className="planks-grid">{friends.map(p=><article key={p.handle}><img src={p.avatarUrl||"/plank-classic.jpeg"} alt=""/><div><a href={`/u/${p.handle}`}>{p.displayName}</a><small>@{p.handle}</small><p>{p.bio||p.mood}</p><button disabled={busy||p.handle==="degenwaffle"} onClick={()=>remove(p.handle)}>{p.handle==="degenwaffle"?"Founding Friend":"Remove Friend"}</button></div></article>)}</div></section><section><h2>All Planks ({all.length})</h2><div className="planks-grid">{all.map(p=><article key={p.handle}><img src={p.avatarUrl||"/plank-classic.jpeg"} alt=""/><div><a href={`/u/${p.handle}`}>{p.displayName}</a><small>@{p.handle}</small><p>{p.bio||p.mood}</p>{!friendHandles.has(p.handle)&&<button disabled={busy||pending.has(p.handle)} onClick={()=>request(p.handle)}>{pending.has(p.handle)?"Request Pending":"Add Friend"}</button>}</div></article>)}</div></section></>}</main></div>;
}
