// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {ReentrancyGuard} from "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import {PullPayment} from "@openzeppelin/contracts/security/PullPayment.sol";
import {VRFConsumerBaseV2Plus} from "@chainlink/contracts/src/v0.8/vrf/dev/VRFConsumerBaseV2Plus.sol";
import {VRFV2PlusClient} from "@chainlink/contracts/src/v0.8/vrf/dev/libraries/VRFV2PlusClient.sol";

/**
 * Plank Crash VRF -- same pari-mutuel game as PlankCrashV2.sol (its header
 * is required reading first; this file only documents the delta), with
 * ONE real architectural change: the crash point's entropy comes from
 * Chainlink VRF instead of blockhash(futureBlock).
 *
 * WHY THIS EXISTS: PlankCrashV2's own header disclosed, honestly, that
 * blockhash-derived randomness is grindable by whoever controls block
 * production -- on Robinhood Chain, that's the single Robinhood-operated
 * sequencer, unilaterally. That risk was bounded in practice (Robinhood
 * has no stake in this game's outcomes) but not eliminated by any code.
 * Chainlink VRF eliminates it structurally, not just bounds it: the
 * random value and a cryptographic proof are generated by an independent
 * oracle network using a keypair the sequencer never sees, verified
 * on-chain before this contract ever acts on it. The sequencer can still
 * decide WHEN the fulfillment transaction lands, but it cannot influence
 * WHAT the random value is -- a structurally different (and stronger)
 * guarantee than "the only party who could grind blocks has no reason
 * to." This is the real, live, industry-standard pattern -- Chainlink
 * VRF already runs three other services (Data Feeds, Data Streams, CCIP)
 * on Robinhood Chain from its July 2026 mainnet launch day one; VRF
 * itself is live on Arbitrum One, the stack Robinhood Chain is built on
 * -- but VRF's specific availability on ROBINHOOD Chain itself was not
 * independently confirmed as part of building this (see the deploy
 * checklist at the bottom of this file). Ship this contract only after
 * confirming that, not before.
 *
 * WHAT'S IDENTICAL TO PlankCrashV2 (same struct shape, same functions,
 * same tests' worth of properties, not re-litigated here): placeBet,
 * carryForwardStake, cashOut (same post-crash-point gate), presetCashOut
 * (same pre-reveal-only fairness gate), settleRound (same reveal/settle
 * split, same maxElapsedBlocks cap, same keeper reward), registerResult,
 * claim, estimatedPayout (same two-regime honesty fix), the whale cap's
 * same honest non-sybil-proof disclosure, the same _multiplierAt curve.
 *
 * WHAT'S DIFFERENT:
 *   - lockRound() requests VRF randomness immediately instead of
 *     computing a future entropyBlock. There is no "entropy not yet
 *     available" window to wait out -- the wait is now "however long the
 *     Chainlink oracle network takes to respond" (typically seconds,
 *     bounded by requestConfirmations), not a fixed block count this
 *     contract controls.
 *   - fulfillRandomWords() (Chainlink's own callback, invoked by the VRF
 *     coordinator -- NOT a permissionless function anyone calls, unlike
 *     revealEntropy() in V2) replaces revealEntropy(). It does exactly
 *     the same derivation V2's revealEntropy did, just triggered
 *     differently.
 *   - voidStaleRequest() replaces voidStaleRound() as the liveness
 *     fallback: if the VRF coordinator never calls back within
 *     maxAwaitBlocks (a real, if rare, failure mode -- an underfunded
 *     subscription, an oracle-network outage), anyone can void the round
 *     and stakes carry forward exactly like V2's fallback.
 *   - OWNERSHIP, DISCLOSED HONESTLY: VRFConsumerBaseV2Plus requires
 *     inheriting ConfirmedOwner (an owner-controlled setCoordinator()
 *     function, so a VRF coordinator migration can be handled). This is
 *     a REAL departure from "no admin lever, anywhere, ever" -- Chainlink
 *     VRF integration cannot be built without accepting SOME owner
 *     surface, and pretending otherwise would be dishonest. The
 *     mitigation is procedural, not architectural, but it is NOT a plain
 *     renounceOwnership() call -- ConfirmedOwner doesn't have one, a real
 *     finding from actually reading its source rather than assuming
 *     OpenZeppelin Ownable-compatible behavior. Its transferOwnership()
 *     is a real two-step handoff, and transferring to address(0)
 *     specifically does NOT renounce anything here: nobody can ever
 *     transact as address(0) to complete the second step, so the
 *     ORIGINAL owner silently keeps permanent control -- the opposite of
 *     the intent. See OwnershipBurner.sol for the real fix: a minimal,
 *     immutable, single-purpose contract that completes the handoff and
 *     exposes nothing else, so ownership lands somewhere no one can ever
 *     use again. This MUST be part of the deploy script, not a manual
 *     step someone might forget -- see the deploy checklist at the
 *     bottom of this file.
 */
contract PlankCrashVRF is ReentrancyGuard, PullPayment, VRFConsumerBaseV2Plus {
    enum Phase {
        BETTING,
        LIVE,
        CRASHED,
        SETTLED
    }

    struct Round {
        Phase phase;
        uint256 bettingEndsAt;
        uint256 lockBlock;
        uint256 vrfRequestId;
        bool entropyRevealed;
        uint256 trueCrashElapsedBlocks;
        uint256 crashElapsedBlocks;
        uint256 crashMultiplierBps;
        uint256 pool;
        uint256 distributable;
        uint256 totalWinningWeight;
        uint256 provisionalWinningWeight;
        uint256 registrationDeadlineBlock;
        uint256 rolledOverFromPrevious;
    }

    uint256 public immutable bettingDurationSeconds;
    uint256 public immutable roundIntervalSeconds;
    uint256 public immutable genesisTimestamp;
    // How long, in blocks, this contract will wait for the VRF
    // coordinator to call fulfillRandomWords() before voidStaleRequest()
    // becomes callable. Not an EVM protocol limit (unlike V1/V2's real
    // 256-block blockhash window) -- a policy choice, generous enough to
    // absorb normal oracle-network latency without false-voiding real
    // rounds, tight enough that a genuinely stuck round doesn't trap
    // stake for long.
    uint256 public immutable maxAwaitBlocks;
    uint256 public immutable maxElapsedBlocks;
    uint256 public immutable registrationWindowBlocks;
    uint256 public immutable rakeBps;
    uint256 public immutable minParticipants;
    uint256 public immutable minPoolSize;
    uint256 public immutable maxStakePerWalletBps;
    uint256 public immutable keeperRewardBps;
    address public immutable treasury;
    uint256 public accumulatedRake;

    // VRF request config -- see Chainlink's own subscription-management
    // docs for keyHash/subscriptionId; requestConfirmations/
    // callbackGasLimit are deploy-time policy choices bounded by the
    // coordinator's own [min, 200] / [0, maxGasLimit] ranges.
    //
    // callbackGasLimit, DISCLOSED HONESTLY -- a real audit finding:
    // fulfillRandomWords() runs _deriveCrash -> _invertMultiplier, a
    // while-loop bounded by a 200,000-iteration hard cap but, for a
    // realistic worst-case entropy draw (r near 9999, the top of the
    // modulo range), converges in roughly ~22,000 iterations before
    // reverting the callback if gas runs out. Coordinators generally do
    // NOT retry a reverted callback -- an undersized callbackGasLimit
    // would mean the statistically rare-but-real high-multiplier outcomes
    // are exactly the ones most likely to force a fulfillment revert (and
    // therefore a voidStaleRequest()-triggered void), a subtle,
    // entropy-correlated bias in which rounds get voided. No funds are
    // ever at risk (voiding only carries stake forward), but deploy
    // scripts MUST size this with the ~22k-iteration case explicitly in
    // mind -- target comfortably above what that costs on the real
    // target chain, not a generic default copied from elsewhere.
    bytes32 public immutable keyHash;
    uint256 public immutable subscriptionId;
    uint16 public immutable requestConfirmations;
    uint32 public immutable callbackGasLimit;

    uint256 public currentRoundId;
    mapping(uint256 => Round) public rounds;
    mapping(uint256 => uint256) public requestIdToRoundId;
    mapping(uint256 => mapping(address => uint256)) public stakeOf;
    mapping(uint256 => mapping(address => uint256)) public cashOutBlockOf;
    mapping(uint256 => mapping(address => bool)) public registered;
    mapping(uint256 => mapping(address => bool)) public claimed;
    mapping(uint256 => mapping(address => uint256)) private _weightOf;
    mapping(uint256 => uint256) public participantCount;
    mapping(uint256 => bool) public voided;
    mapping(uint256 => mapping(address => bool)) public carriedForward;

    event RoundStarted(uint256 indexed roundId, uint256 bettingEndsAt);
    event BetPlaced(uint256 indexed roundId, address indexed player, uint256 amount);
    event RoundLocked(uint256 indexed roundId, uint256 lockBlock, uint256 vrfRequestId);
    event RoundVoided(uint256 indexed roundId, uint256 rolledOverPool, string reason);
    event CashedOut(uint256 indexed roundId, address indexed player, uint256 atBlock, bool preset);
    event EntropyRevealed(uint256 indexed roundId, uint256 trueCrashMultiplierBps, uint256 trueCrashElapsedBlocks);
    event RoundCrashed(uint256 indexed roundId, uint256 crashMultiplierBps, uint256 crashElapsedBlocks, bool cappedByMax);
    event ResultRegistered(uint256 indexed roundId, address indexed player, bool won, uint256 weight);
    event Claimed(uint256 indexed roundId, address indexed player, uint256 payout);

    error BadPhase();
    error TooEarly();
    error TooLate();
    error AlreadyBet();
    error NoBet();
    error AlreadyCashedOut();
    error AlreadyRegistered();
    error AlreadyClaimed();
    error NotWinner();
    error StakeExceedsCap();
    error EntropyNotRevealed();
    error EntropyAlreadyRevealed();
    error CrashPointNotYetReached();
    error PastCrashPoint();
    error TargetUnreachable();
    error UnknownRequestId();

    struct Config {
        uint256 bettingDurationSeconds;
        uint256 roundIntervalSeconds;
        uint256 maxAwaitBlocks;
        uint256 maxElapsedBlocks;
        uint256 registrationWindowBlocks;
        uint256 rakeBps;
        uint256 minParticipants;
        uint256 minPoolSize;
        uint256 maxStakePerWalletBps;
        uint256 keeperRewardBps;
        address treasury;
        address vrfCoordinator;
        bytes32 keyHash;
        uint256 subscriptionId;
        uint16 requestConfirmations;
        uint32 callbackGasLimit;
    }

    constructor(Config memory cfg) VRFConsumerBaseV2Plus(cfg.vrfCoordinator) {
        bettingDurationSeconds = cfg.bettingDurationSeconds;
        roundIntervalSeconds = cfg.roundIntervalSeconds;
        genesisTimestamp = block.timestamp;
        maxAwaitBlocks = cfg.maxAwaitBlocks;
        maxElapsedBlocks = cfg.maxElapsedBlocks;
        registrationWindowBlocks = cfg.registrationWindowBlocks;
        rakeBps = cfg.rakeBps;
        minParticipants = cfg.minParticipants;
        minPoolSize = cfg.minPoolSize;
        maxStakePerWalletBps = cfg.maxStakePerWalletBps;
        keeperRewardBps = cfg.keeperRewardBps;
        treasury = cfg.treasury;
        keyHash = cfg.keyHash;
        subscriptionId = cfg.subscriptionId;
        requestConfirmations = cfg.requestConfirmations;
        callbackGasLimit = cfg.callbackGasLimit;
        _startRound(0);
    }

    // ── Round lifecycle ──────────────────────────────────────────────────

    function _nextSlot() private view returns (uint256) {
        uint256 elapsed = block.timestamp - genesisTimestamp;
        uint256 k = (elapsed / roundIntervalSeconds) + 1;
        return genesisTimestamp + k * roundIntervalSeconds;
    }

    function _startRound(uint256 rolledOver) private {
        currentRoundId += 1;
        Round storage r = rounds[currentRoundId];
        r.phase = Phase.BETTING;
        r.bettingEndsAt = (currentRoundId == 1 || roundIntervalSeconds == 0)
            ? block.timestamp + bettingDurationSeconds
            : _nextSlot();
        r.pool = rolledOver;
        r.rolledOverFromPrevious = rolledOver;
        emit RoundStarted(currentRoundId, r.bettingEndsAt);
    }

    function placeBet() external payable nonReentrant {
        Round storage r = rounds[currentRoundId];
        if (r.phase != Phase.BETTING) revert BadPhase();
        if (block.timestamp >= r.bettingEndsAt) revert TooLate();
        if (stakeOf[currentRoundId][msg.sender] != 0) revert AlreadyBet();

        uint256 poolAfter = r.pool + msg.value;
        if (r.pool != 0 && msg.value * 10000 > poolAfter * maxStakePerWalletBps) {
            revert StakeExceedsCap();
        }

        stakeOf[currentRoundId][msg.sender] = msg.value;
        r.pool = poolAfter;
        participantCount[currentRoundId] += 1;
        emit BetPlaced(currentRoundId, msg.sender, msg.value);
    }

    function carryForwardStake(uint256 fromRoundId) external nonReentrant {
        if (!voided[fromRoundId]) revert BadPhase();
        if (carriedForward[fromRoundId][msg.sender]) revert AlreadyClaimed();
        uint256 amount = stakeOf[fromRoundId][msg.sender];
        if (amount == 0) revert NoBet();

        Round storage cur = rounds[currentRoundId];
        if (cur.phase != Phase.BETTING) revert BadPhase();
        if (stakeOf[currentRoundId][msg.sender] != 0) revert AlreadyBet();

        uint256 poolAfter = cur.pool + amount;
        if (cur.pool != 0 && amount * 10000 > poolAfter * maxStakePerWalletBps) {
            revert StakeExceedsCap();
        }

        carriedForward[fromRoundId][msg.sender] = true;
        stakeOf[currentRoundId][msg.sender] = amount;
        cur.pool = poolAfter;
        participantCount[currentRoundId] += 1;
        emit BetPlaced(currentRoundId, msg.sender, amount);
    }

    /// Locks the round AND immediately requests VRF randomness -- no
    /// separate "wait for a future block to exist" step, unlike V2. The
    /// wait now is "however long the oracle network takes", bounded by
    /// requestConfirmations on the low end and maxAwaitBlocks on the high
    /// end (voidStaleRequest()).
    function lockRound() external nonReentrant {
        uint256 id = currentRoundId;
        Round storage r = rounds[id];
        if (r.phase != Phase.BETTING) revert BadPhase();
        if (block.timestamp < r.bettingEndsAt) revert TooEarly();

        if (participantCount[id] < minParticipants || r.pool < minPoolSize) {
            emit RoundVoided(id, r.pool, "under-threshold");
            voided[id] = true;
            r.phase = Phase.SETTLED;
            _startRound(0);
            return;
        }

        r.phase = Phase.LIVE;
        r.lockBlock = block.number;
        uint256 requestId = s_vrfCoordinator.requestRandomWords(
            VRFV2PlusClient.RandomWordsRequest({
                keyHash: keyHash,
                subId: subscriptionId,
                requestConfirmations: requestConfirmations,
                callbackGasLimit: callbackGasLimit,
                numWords: 1,
                extraArgs: VRFV2PlusClient._argsToBytes(VRFV2PlusClient.ExtraArgsV1({nativePayment: false}))
            })
        );
        r.vrfRequestId = requestId;
        requestIdToRoundId[requestId] = id;
        emit RoundLocked(id, r.lockBlock, requestId);
    }

    function cashOut(uint256 roundId) external nonReentrant {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.LIVE) revert BadPhase();
        if (stakeOf[roundId][msg.sender] == 0) revert NoBet();
        if (cashOutBlockOf[roundId][msg.sender] != 0) revert AlreadyCashedOut();
        uint256 elapsed = block.number - r.lockBlock;
        if (r.entropyRevealed && elapsed >= _effectiveCrashElapsed(r)) revert PastCrashPoint();
        cashOutBlockOf[roundId][msg.sender] = block.number;
        r.provisionalWinningWeight += (stakeOf[roundId][msg.sender] * _multiplierAt(elapsed)) / 10000;
        emit CashedOut(roundId, msg.sender, block.number, false);
    }

    function presetCashOut(uint256 roundId, uint256 targetMultiplierBps) external nonReentrant {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.LIVE) revert BadPhase();
        if (r.entropyRevealed) revert EntropyAlreadyRevealed();
        if (stakeOf[roundId][msg.sender] == 0) revert NoBet();
        if (cashOutBlockOf[roundId][msg.sender] != 0) revert AlreadyCashedOut();

        if (_multiplierAt(maxElapsedBlocks) < targetMultiplierBps) revert TargetUnreachable();
        uint256 targetElapsed = _invertMultiplier(targetMultiplierBps);

        cashOutBlockOf[roundId][msg.sender] = r.lockBlock + targetElapsed;
        r.provisionalWinningWeight += (stakeOf[roundId][msg.sender] * _multiplierAt(targetElapsed)) / 10000;
        emit CashedOut(roundId, msg.sender, r.lockBlock + targetElapsed, true);
    }

    /// Chainlink's own callback -- NOT permissionless in the sense
    /// revealEntropy() was. Only the VRF coordinator can ever cause this
    /// to run (enforced by rawFulfillRandomWords in the base contract,
    /// checked against s_vrfCoordinator). Does exactly what V2's
    /// revealEntropy() did with the derived randomness once it's here.
    function fulfillRandomWords(uint256 requestId, uint256[] calldata randomWords) internal override {
        uint256 roundId = requestIdToRoundId[requestId];
        if (roundId == 0) revert UnknownRequestId();
        Round storage r = rounds[roundId];
        if (r.phase != Phase.LIVE) revert BadPhase();
        if (r.entropyRevealed) revert EntropyAlreadyRevealed();

        (uint256 trueMultiplierBps, uint256 trueElapsed) = _deriveCrash(bytes32(randomWords[0]));
        r.trueCrashElapsedBlocks = trueElapsed;
        r.entropyRevealed = true;
        emit EntropyRevealed(roundId, trueMultiplierBps, trueElapsed);
    }

    function settleRound(uint256 roundId) external nonReentrant {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.LIVE) revert BadPhase();
        if (!r.entropyRevealed) revert EntropyNotRevealed();
        uint256 effective = _effectiveCrashElapsed(r);
        if (block.number - r.lockBlock < effective) revert CrashPointNotYetReached();

        r.crashElapsedBlocks = effective;
        r.crashMultiplierBps = _multiplierAt(effective);
        r.distributable = (r.pool * (10000 - rakeBps)) / 10000;
        r.registrationDeadlineBlock = block.number + registrationWindowBlocks;
        r.phase = Phase.CRASHED;

        uint256 rake = r.pool - r.distributable;
        uint256 keeperReward = (rake * keeperRewardBps) / 10000;
        accumulatedRake += rake - keeperReward;
        if (keeperReward > 0) _asyncTransfer(msg.sender, keeperReward);

        emit RoundCrashed(roundId, r.crashMultiplierBps, effective, r.trueCrashElapsedBlocks > maxElapsedBlocks);
        _startRound(0);
    }

    /// Liveness fallback for VRF's real (if rare) failure modes: an
    /// underfunded subscription, an oracle-network outage, a coordinator
    /// migration mid-flight. Without this, a round the coordinator never
    /// calls back for would hang in LIVE forever with real stake trapped
    /// in it -- the same shape of gap V2's voidStaleRound() closes for
    /// blockhash's 256-block expiry, just for a different real failure
    /// mode.
    function voidStaleRequest(uint256 roundId) external nonReentrant {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.LIVE) revert BadPhase();
        if (r.entropyRevealed) revert EntropyAlreadyRevealed();
        if (block.number <= r.lockBlock + maxAwaitBlocks) revert TooEarly();

        emit RoundVoided(roundId, r.pool, "vrf-fulfillment-timeout");
        voided[roundId] = true;
        r.phase = Phase.SETTLED;
        _startRound(0);
    }

    function claimRake() external nonReentrant {
        uint256 amount = accumulatedRake;
        accumulatedRake = 0;
        _asyncTransfer(treasury, amount);
    }

    function registerResult(uint256 roundId) external nonReentrant {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.CRASHED) revert BadPhase();
        if (block.number > r.registrationDeadlineBlock) revert TooLate();
        uint256 stake = stakeOf[roundId][msg.sender];
        if (stake == 0) revert NoBet();
        if (registered[roundId][msg.sender]) revert AlreadyRegistered();
        registered[roundId][msg.sender] = true;

        uint256 cashOutBlock = cashOutBlockOf[roundId][msg.sender];
        bool won = cashOutBlock != 0 && (cashOutBlock - r.lockBlock) <= r.crashElapsedBlocks;

        uint256 weight = 0;
        if (won) {
            uint256 multiplierAtCashOutBps = _multiplierAt(cashOutBlock - r.lockBlock);
            weight = (stake * multiplierAtCashOutBps) / 10000;
            r.totalWinningWeight += weight;
        }
        emit ResultRegistered(roundId, msg.sender, won, weight);
        _weightOf[roundId][msg.sender] = weight;
    }

    function claim(uint256 roundId) external nonReentrant {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.CRASHED) revert BadPhase();
        if (block.number <= r.registrationDeadlineBlock) revert TooEarly();
        if (!registered[roundId][msg.sender]) revert NotWinner();
        if (claimed[roundId][msg.sender]) revert AlreadyClaimed();
        uint256 weight = _weightOf[roundId][msg.sender];
        if (weight == 0) revert NotWinner();

        claimed[roundId][msg.sender] = true;
        uint256 payout = (r.distributable * weight) / r.totalWinningWeight;
        _asyncTransfer(msg.sender, payout);
        emit Claimed(roundId, msg.sender, payout);
    }

    // ── Pure math -- byte-for-byte identical to PlankCrashV2's, not ──────
    // ── re-derived, so both contracts pay out the exact same curve ──────

    function _effectiveCrashElapsed(Round storage r) private view returns (uint256) {
        return r.trueCrashElapsedBlocks < maxElapsedBlocks ? r.trueCrashElapsedBlocks : maxElapsedBlocks;
    }

    function _multiplierAt(uint256 elapsedBlocks) public pure returns (uint256) {
        return 10000 + (elapsedBlocks * 40) + (elapsedBlocks * elapsedBlocks) / 5;
    }

    function _invertMultiplier(uint256 targetBps) public pure returns (uint256 elapsedBlocks) {
        elapsedBlocks = 0;
        while (_multiplierAt(elapsedBlocks) < targetBps && elapsedBlocks <= 200000) {
            elapsedBlocks++;
        }
    }

    function _deriveCrash(bytes32 entropy) public pure returns (uint256 multiplierBps, uint256 elapsedBlocks) {
        uint256 r = uint256(entropy) % 10000;
        if (r == 0) {
            return (10000, 0);
        }
        multiplierBps = (10000 * 10000) / (10000 - r);
        elapsedBlocks = _invertMultiplier(multiplierBps);
    }

    // ── View helpers for the frontend ────────────────────────────────────

    function currentRound() external view returns (Round memory) {
        return rounds[currentRoundId];
    }

    function liveMultiplierBps(uint256 roundId) external view returns (uint256) {
        Round storage r = rounds[roundId];
        if (r.phase != Phase.LIVE) return 0;
        uint256 elapsed = block.number - r.lockBlock;
        if (r.entropyRevealed) {
            uint256 effective = _effectiveCrashElapsed(r);
            if (elapsed > effective) elapsed = effective;
        }
        return _multiplierAt(elapsed);
    }

    function estimatedPayout(uint256 roundId, address player) external view returns (uint256) {
        Round storage r = rounds[roundId];
        uint256 cashOutBlock = cashOutBlockOf[roundId][player];
        if (cashOutBlock == 0) return 0;

        if (r.phase == Phase.CRASHED || r.phase == Phase.SETTLED) {
            bool won = (cashOutBlock - r.lockBlock) <= r.crashElapsedBlocks;
            if (!won) return 0;
            uint256 realWeight = (stakeOf[roundId][player] * _multiplierAt(cashOutBlock - r.lockBlock)) / 10000;
            if (r.totalWinningWeight > 0) {
                return (r.distributable * realWeight) / r.totalWinningWeight;
            }
            if (r.provisionalWinningWeight == 0) return 0;
            return (r.distributable * realWeight) / r.provisionalWinningWeight;
        }

        if (r.provisionalWinningWeight == 0) return 0;
        uint256 myWeight = (stakeOf[roundId][player] * _multiplierAt(cashOutBlock - r.lockBlock)) / 10000;
        uint256 distributableNow = (r.pool * (10000 - rakeBps)) / 10000;
        return (distributableNow * myWeight) / r.provisionalWinningWeight;
    }
}

/*
 * DEPLOY CHECKLIST -- read before mainnet, not after:
 *   [ ] Confirm Chainlink VRF v2.5 is actually live on Robinhood Chain
 *       (not just Data Feeds/Data Streams/CCIP, which are confirmed live
 *       from mainnet launch -- VRF is a separate service with its own
 *       per-chain deployment). If it isn't live there yet, this contract
 *       is not deployable there yet -- PlankCrashV2.sol (blockhash-based,
 *       sequencer-trust-bounded) is the interim option, not this one.
 *   [ ] Create and fund a real VRF subscription; add this contract's
 *       address as a consumer.
 *   [ ] Deploy, verify s_vrfCoordinator() returns the expected coordinator
 *       address, then deploy OwnershipBurner(address(this)), call
 *       transferOwnership(address(burner)), then burner.burn() -- all in
 *       the SAME deploy script (not a manual follow-up step). See
 *       OwnershipBurner.sol and the contract header's OWNERSHIP section
 *       for why a plain renounceOwnership() call does not exist here and
 *       would be the wrong instruction if it did.
 *   [ ] Monitor subscription LINK/native balance -- an underfunded
 *       subscription is exactly the failure mode voidStaleRequest()
 *       exists for, but repeated void-and-refund cycles are a bad player
 *       experience even though nobody's funds are ever at risk.
 */
