import {desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {postLikes,posts,profileComments,reports} from "../../../db/schema";
import {hashJson} from "../auth/hash";
import {type Proof,verifyAndConsumeProof} from "../auth/verify";
const ADMINS=new Set(["0x269a93ec8486fbc3a82e352430e84fd8af8ebb0d","0x7304b78e28370f45fdf77ca67bdbbf550c3aac34"]);
const clean=(v:unknown,n=300)=>String(v||"").trim().slice(0,n);

export async function POST(request:Request){const p=await request.json() as Proof&{targetType?:string;targetId?:string;reason?:string},targetType=p.targetType||"",targetId=clean(p.targetId,80),reason=clean(p.reason),data={targetType,targetId,reason},wallet=await verifyAndConsumeProof(p,"report:create",`${targetType}:${targetId}`,await hashJson(data));if(!wallet||!new Set(["profile","post","comment"]).has(targetType)||!targetId||!reason)return Response.json({error:"Wallet verification and a reason are required"},{status:403});await getDb().insert(reports).values({reporterWallet:wallet,targetType,targetId,reason});return Response.json({reported:true},{status:201})}
export async function DELETE(request:Request){const p=await request.json() as Proof&{targetType?:string;targetId?:string},targetType=p.targetType||"",targetId=clean(p.targetId,80),wallet=await verifyAndConsumeProof(p,targetType==="post"?"post:delete":"comment:delete",`${targetType}:${targetId}`,await hashJson({targetType,targetId}));if(!wallet||!/^(post|comment)$/.test(targetType)||!/^\d+$/.test(targetId))return Response.json({error:"Wallet verification required"},{status:403});const db=getDb(),id=Number(targetId);if(targetType==="post"){const [row]=await db.select().from(posts).where(eq(posts.id,id)).limit(1);if(!row||row.authorWallet!==wallet)return Response.json({error:"Post not found"},{status:404});await db.delete(postLikes).where(eq(postLikes.postId,id));await db.delete(posts).where(eq(posts.id,id))}else{const [row]=await db.select().from(profileComments).where(eq(profileComments.id,id)).limit(1);if(!row||row.authorWallet!==wallet)return Response.json({error:"Comment not found"},{status:404});await db.delete(profileComments).where(eq(profileComments.id,id))}return Response.json({deleted:true})}
export async function GET(request:Request){const url=new URL(request.url),wallet=(url.searchParams.get("wallet")||"").toLowerCase(),sessionToken=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"",verified=await verifyAndConsumeProof({wallet,sessionToken},"admin:content","admin","");if(!verified||!ADMINS.has(verified))return Response.json({error:"Admin wallet verification required"},{status:403});const db=getDb();return Response.json({reports:await db.select().from(reports).orderBy(desc(reports.id)).limit(250),posts:await db.select().from(posts).orderBy(desc(posts.id)).limit(100),comments:await db.select().from(profileComments).orderBy(desc(profileComments.id)).limit(100)})}
export async function PATCH(request:Request){const p=await request.json() as Proof&{kind?:string;id?:number;status?:string;resolution?:string},wallet=await verifyAndConsumeProof(p,"admin:content","admin","");if(!wallet||!ADMINS.has(wallet))return Response.json({error:"Admin wallet verification required"},{status:403});const db=getDb();if(p.kind==="report"&&Number.isInteger(p.id)){await db.update(reports).set({status:p.status==="dismissed"?"dismissed":"resolved",resolution:clean(p.resolution)}).where(eq(reports.id,p.id!));return Response.json({updated:true})}if((p.kind==="post"||p.kind==="comment")&&Number.isInteger(p.id)){const status=p.status==="removed"?"removed":"approved";if(p.kind==="post")await db.update(posts).set({moderationStatus:status}).where(eq(posts.id,p.id!));else await db.update(profileComments).set({moderationStatus:status}).where(eq(profileComments.id,p.id!));return Response.json({updated:true})}return Response.json({error:"Invalid moderation action"},{status:400})}
