import { rateLimit } from "@/lib/security";
import { readPublicText } from "@/lib/public-json";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/**
 * Serve pre-built holder airdrop files from public/exports
 * (generated by: node scripts/holder-airdrop-audit.mjs)
 *
 * GET /api/airdrop/export-holders?format=20lab|full|json|txt
 */
export async function GET(req: Request) {
  const limited = rateLimit(req, {
    key: "airdrop-export-holders",
    limit: 30,
    windowMs: 60_000,
  });
  if (limited) return limited;

  const url = new URL(req.url);
  const format = (url.searchParams.get("format") || "20lab").toLowerCase();

  const files: Record<string, { name: string; type: string }> = {
    "20lab": {
      name: "plank-airdrop-20lab.csv",
      type: "text/csv; charset=utf-8",
    },
    csv: {
      name: "plank-airdrop-20lab.csv",
      type: "text/csv; charset=utf-8",
    },
    txt: {
      name: "plank-airdrop-20lab.txt",
      type: "text/plain; charset=utf-8",
    },
    full: {
      name: "plank-airdrop-full.csv",
      type: "text/csv; charset=utf-8",
    },
    json: {
      name: "plank-holders-audit.json",
      type: "application/json; charset=utf-8",
    },
  };

  const meta = files[format] || files["20lab"];
  const body = await readPublicText(`public/exports/${meta.name}`);

  if (body == null) {
    return new Response(
      JSON.stringify({
        error: "NOT_BUILT",
        message:
          "Holder export not built yet. Run: node scripts/holder-airdrop-audit.mjs",
      }),
      {
        status: 404,
        headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
      }
    );
  }

  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": meta.type,
      "Content-Disposition": `attachment; filename="${meta.name}"`,
      "Cache-Control": "no-store",
    },
  });
}
