"use client";
import Link from "next/link";
/* eslint-disable @next/next/no-img-element */
import {useMemo,useState} from "react";
import {connectPlankLoveWallet} from "../plank-love-wallet";
import {walletProof} from "../auth-client";

type Profile={wallet:string;handle:string;displayName:string;bio:string;avatarUrl:string;moderationStatus:string;createdAt:string;updatedAt:string};
const ADMINS=new Set(["0x269a93ec8486fbc3a82e352430e84fd8af8ebb0d","0x7304b78e28370f45fdf77ca67bdbbf550c3aac34"]);

export default function Admin(){
 const [wallet,setWallet]=useState(""),[items,setItems]=useState<Profile[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[note,setNote]=useState(""),[autoApprove,setAutoApprove]=useState(false);
 const request=async(body:Record<string,unknown>,address=wallet)=>{const action=String(body.action),resource=action==="moderate"?String(body.profileWallet):"admin",data=body,proof=await walletProof(address,`admin:${action}`,resource,data),result=await fetch("/api/admin/profiles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,...proof,wallet:address})}).then(r=>r.json());if(result.error)throw new Error(result.error);setItems(result.profiles||[]);setAutoApprove(Boolean(result.settings?.autoApproveProfiles))};
 const connect=async()=>{setBusy(true);setError("");try{const address=await connectPlankLoveWallet();if(!ADMINS.has(address))throw new Error("This wallet is not an approved PlankSpace admin.");await request({action:"list"},address);setWallet(address)}catch(e){setError(e instanceof Error?e.message:"Admin connection failed")}finally{setBusy(false)}};
 const moderate=async(profileWallet:string,status:"approved"|"pending"|"removed")=>{if(status==="removed"&&!confirm("Remove this profile from public view?"))return;setBusy(true);setError("");try{await request({action:"moderate",profileWallet,status,note})}catch(e){setError(e instanceof Error?e.message:"Moderation failed")}finally{setBusy(false)}};
 const changeAutoApprove=async(enabled:boolean)=>{setBusy(true);setError("");try{await request({action:"settings",enabled})}catch(e){setError(e instanceof Error?e.message:"Setting update failed")}finally{setBusy(false)}};
 const approveAll=async()=>{if(!confirm("Approve every profile currently waiting for review?"))return;setBusy(true);setError("");try{await request({action:"approve-all"})}catch(e){setError(e instanceof Error?e.message:"Bulk approval failed")}finally{setBusy(false)}};
 const shown=useMemo(()=>items.filter(p=>(filter==="all"||p.moderationStatus===filter)&&`${p.displayName} ${p.handle}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 return <div className="admin-shell"><header className="page-bar"><h1>Owner&apos;s woodshop</h1><Link href="/browse">Public directory</Link></header><main><section className="admin-hero"><h2>PlankSpace Admin</h2><p>Visible only to the verified DegenWaffle and Sawtoshi admin wallets.</p>{!wallet?<button onClick={connect} disabled={busy}>{busy?"Connecting…":"Connect Admin Wallet & Verify"}</button>:<><code>{wallet.slice(0,6)}…{wallet.slice(-4)}</code><p><a href="/plankspace/admin/content">Open content reports and moderation →</a></p></>}{error&&<strong role="alert">{error}</strong>}</section>{wallet&&<><section className="admin-tools"><label>Search profiles<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or username"/></label><label>Moderation note<input value={note} onChange={e=>setNote(e.target.value)} maxLength={300} placeholder="Reason for this action"/></label></section><section className="admin-profile-policy"><div><small>NEW PROFILE POLICY</small><h2>All accounts approved</h2><p>{autoApprove?"New profiles become public immediately.":"New profiles stay private until an admin approves them."}</p></div><label><input type="checkbox" checked={autoApprove} disabled={busy} onChange={e=>changeAutoApprove(e.target.checked)}/><span>{autoApprove?"ON":"OFF"}</span></label><button disabled={busy||!items.some(x=>x.moderationStatus==="pending")} onClick={approveAll}>Approve all pending now</button></section><section className="admin-stats">{["all","pending","approved","removed"].map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}><b>{s==="all"?items.length:items.filter(x=>x.moderationStatus===s).length}</b><span>{s}</span></button>)}</section><section className="admin-list">{shown.map(p=><article key={p.wallet}><img src={p.avatarUrl||"/plank-classic.jpeg"} alt=""/><div><h2>{p.displayName} <span>@{p.handle}</span></h2><p>{p.bio||"No bio yet."}</p></div><div className="moderation-actions"><b>{p.moderationStatus}</b><a href={`/u/${p.handle}`}>View</a>{p.moderationStatus!=="approved"&&<button onClick={()=>moderate(p.wallet,"approved")}>Approve</button>}{p.moderationStatus!=="pending"&&<button onClick={()=>moderate(p.wallet,"pending")}>Hold</button>}{p.moderationStatus!=="removed"&&<button onClick={()=>moderate(p.wallet,"removed")}>Remove</button>}</div></article>)}</section></>}</main></div>;
}
