import {createHash} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {homeActor,requireHomeRight} from "./home-access-store";
import {YardError} from "./errors";
import manifest from "./geometry/native-adventure-d4-s63.json";
export async function assistAvailable(c:PoolClient,encounterId:string,helperId:string,controllerId:string|null){
 if(!controllerId||!(await c.query("SELECT to_regclass('charmville_battle_assists') AS present")).rows[0].present)return false;
 return !!(await c.query("SELECT 1 FROM charmville_battle_assists g JOIN charmville_world_presence w ON w.profile_id=g.controller_id JOIN plankspace_profiles p ON p.id=w.profile_id JOIN charmville_encounters e ON e.id=g.encounter_id WHERE g.encounter_id=$1 AND g.helper_id=$2 AND g.controller_id=$3 AND NOT g.consumed AND g.expires_at>clock_timestamp() AND w.expires_at>clock_timestamp() AND p.moderation_status='approved' AND e.lease_until>clock_timestamp() AND e.mode='turn' AND e.region_id=CASE WHEN w.home_owner_id IS NULL THEN 'public:meadow' ELSE 'home:'||w.home_owner_id::text END AND (w.home_owner_id IS NULL OR w.profile_id=w.home_owner_id OR EXISTS(SELECT 1 FROM charmville_home_grants h WHERE h.owner_profile_id=w.home_owner_id AND h.visitor_profile_id=w.profile_id AND h.revoked_at IS NULL AND h.expires_at>clock_timestamp() AND 'visit'=ANY(h.rights)))",[encounterId,helperId,controllerId])).rowCount;
}
export async function inviteBattleAssist(pool:Pool,token:string,raw:unknown){const c=await pool.connect();try{
 const q=raw as Record<string,unknown>|null;if(!q||typeof q.helperProfileId!=="string"||!/^\d{1,18}$/.test(q.helperProfileId)||typeof q.requestId!=="string"||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(q.requestId)||typeof q.revision!=="string"||Object.keys(q).some(k=>!["helperProfileId","requestId","revision","actorEpoch"].includes(k)))throw new YardError("Choose a nearby player",400);
 await c.query("BEGIN");const id=await homeActor(c,token);const p=(await c.query("SELECT home_owner_id::text AS owner,expires_at>clock_timestamp() AS active FROM charmville_world_presence WHERE profile_id=$1 FOR UPDATE",[id])).rows[0];if(!p?.active||q.helperProfileId===id)throw new YardError("Choose another nearby player",403);if(p.owner){if(!(await c.query("SELECT 1 FROM plankspace_profiles WHERE id=$1 AND moderation_status='approved'",[p.owner])).rowCount)throw new YardError("Home unavailable",403);await requireHomeRight(c,p.owner,id,"visit");}
 const region=p.owner?`home:${p.owner}`:"public:meadow",a=(await c.query("SELECT * FROM charmville_native_actors WHERE profile_id=$1 FOR UPDATE",[id])).rows[0],e=(await c.query("SELECT *,lease_until>clock_timestamp() AS live FROM charmville_encounters WHERE region_id=$1 FOR UPDATE",[region])).rows[0];
 if(!a||a.region_id!==region||a.geometry_revision!==manifest.revision||Math.hypot(a.x-4,a.y-9)>2.5||!e||String(e.controller_id)!==id||!e.live||e.mode!=="turn")throw new YardError("Control this nearby encounter first",403);
 const hash=createHash("sha256").update(JSON.stringify(["invite-assist",q.helperProfileId,q.revision,q.actorEpoch])).digest("hex"),prior=(await c.query("SELECT payload_hash,result FROM charmville_battle_receipts WHERE profile_id=$1 AND request_id=$2",[id,q.requestId])).rows[0];if(prior){if(prior.payload_hash!==hash)throw new YardError("Request ID already used",409);await c.query("COMMIT");return prior.result;}
 if(q.revision!==String(e.revision)||q.actorEpoch!==Number(a.region_epoch))throw new YardError("Encounter changed. Refresh",409);
 const helper=(await c.query(`SELECT 1 FROM charmville_world_presence w JOIN plankspace_profiles p ON p.id=w.profile_id JOIN charmville_native_actors a ON a.profile_id=p.id WHERE p.id=$1 AND p.moderation_status='approved' AND w.expires_at>clock_timestamp() AND w.home_owner_id IS NOT DISTINCT FROM $2::bigint AND a.region_id=$3 AND a.geometry_revision=$4 AND (a.x-4)*(a.x-4)+(a.y-9)*(a.y-9)<=6.25 AND (w.home_owner_id IS NULL OR w.profile_id=w.home_owner_id OR EXISTS(SELECT 1 FROM charmville_home_grants g WHERE g.owner_profile_id=w.home_owner_id AND g.visitor_profile_id=w.profile_id AND g.revoked_at IS NULL AND g.expires_at>clock_timestamp() AND 'visit'=ANY(g.rights)))`,[q.helperProfileId,p.owner,region,manifest.revision])).rowCount;if(!helper)throw new YardError("Helper is not nearby or authorized",403);
 await c.query("INSERT INTO charmville_battle_assists(encounter_id,controller_id,helper_id,expires_at) VALUES($1,$2,$3,LEAST($4::timestamptz,clock_timestamp()+interval '30 seconds')) ON CONFLICT(encounter_id) DO UPDATE SET controller_id=EXCLUDED.controller_id,helper_id=EXCLUDED.helper_id,expires_at=EXCLUDED.expires_at,consumed=false",[e.id,id,q.helperProfileId,e.lease_until]);const expiry=(await c.query("SELECT expires_at FROM charmville_battle_assists WHERE encounter_id=$1",[e.id])).rows[0].expires_at.toISOString();const result={granted:true,helperProfileId:q.helperProfileId,expiresAt:expiry};await c.query("INSERT INTO charmville_battle_receipts VALUES($1,$2,$3,$4::jsonb)",[id,q.requestId,hash,JSON.stringify(result)]);await c.query("COMMIT");return result;
 }catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}


