import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { xAccounts, xOAuthStates } from "../../../../db/schema";
import { encryptXCredential } from "../../../x/crypto";

async function jsonBody<T>(response:Response):Promise<T|null>{const text=await response.text();if(!text)return null;try{return JSON.parse(text) as T}catch{return null}}
const redirect=(url:URL,status:string)=>Response.redirect(new URL(`/profile-editor?x=${status}#connections`,url));

export async function GET(request:Request){const url=new URL(request.url),state=url.searchParams.get("state")||"",code=url.searchParams.get("code")||"",db=getDb(),[pending]=await db.select().from(xOAuthStates).where(eq(xOAuthStates.state,state)).limit(1);if(!pending||!code||Date.parse(pending.expiresAt)<Date.now())return redirect(url,"invalid");await db.delete(xOAuthStates).where(eq(xOAuthStates.state,state));const clientId=process.env.X_CLIENT_ID||"",redirectUri=process.env.X_REDIRECT_URI||"",form=new URLSearchParams({code,grant_type:"authorization_code",client_id:clientId,redirect_uri:redirectUri,code_verifier:pending.pkceVerifier}),headers:Record<string,string>={"content-type":"application/x-www-form-urlencoded"};if(process.env.X_CLIENT_SECRET)headers.authorization=`Basic ${Buffer.from(`${clientId}:${process.env.X_CLIENT_SECRET}`).toString("base64")}`;const tokenResponse=await fetch("https://api.x.com/2/oauth2/token",{method:"POST",headers,body:form}),tokens=await jsonBody<{access_token?:string;refresh_token?:string;expires_in?:number}>(tokenResponse);if(!tokenResponse.ok||!tokens?.access_token)return redirect(url,"failed");const meResponse=await fetch("https://api.x.com/2/users/me",{headers:{authorization:`Bearer ${tokens.access_token}`}}),me=await jsonBody<{data?:{id:string;username:string}}>(meResponse);if(!meResponse.ok||!me?.data)return redirect(url,"failed");const values={profileHandle:pending.profileHandle,xUserId:me.data.id,xUsername:me.data.username,accessTokenEncrypted:encryptXCredential(tokens.access_token),refreshTokenEncrypted:tokens.refresh_token?encryptXCredential(tokens.refresh_token):"",tokenExpiresAt:tokens.expires_in?new Date(Date.now()+tokens.expires_in*1000).toISOString():null,syncCursor:"",updatedAt:new Date().toISOString()};await db.insert(xAccounts).values({wallet:pending.wallet,...values}).onConflictDoUpdate({target:xAccounts.wallet,set:values});return redirect(url,"connected")}
